import { Router } from "express";
import { authenticate } from "../../middlewares/auth";
import { requireAnyPermission, requirePermission } from "../../middlewares/rbac";
import { uploadAttachment } from "../../middlewares/upload";
import * as c from "./activities.controller";
const router = Router(); router.use(authenticate);
router.get("/indicators", requirePermission("activities.read"), c.indicators);
router.get("/employees", requirePermission("activities.read.all"), c.employees);
router.post("/ai-suggest", requirePermission("activities.create"), c.aiSuggest);
router.post("/attachments", requirePermission("activities.create"), uploadAttachment.single("file"), c.upload);
router.get("/", requirePermission("activities.read"), c.list);
router.post("/", requirePermission("activities.create"), c.create);
router.get("/:id/pdf", requirePermission("activities.export"), c.pdf);
router.get("/:id", requirePermission("activities.read"), c.get);
router.put("/:id", requireAnyPermission(["activities.edit", "activities.edit.all"]), c.update);
router.patch("/:id/status", requireAnyPermission(["activities.complete", "activities.cancel"]), c.changeStatus);
router.post("/:id/signatures", requirePermission("activities.sign"), c.sign);
router.delete("/:id", requireAnyPermission(["activities.edit", "activities.delete"]), c.remove);
export default router;
