import { ActivityStatus, Prisma } from "@prisma/client";
import { prisma } from "../../prisma";
import { BadRequestError, ForbiddenError, NotFoundError } from "../../utils/ApiError";
import type { ActivityInput } from "./activities.schema";
import type { AuthUser } from "../../types/express";

const include = { employee: { select: { id: true, name: true, sector: true, position: true } }, createdBy: { select: { id: true, name: true } }, materials: { include: { product: { select: { id: true, name: true, code: true, unit: true } } } }, problems: { include: { attachments: true } }, attachments: { where: { problemId: null } }, signatures: { include: { signedBy: { select: { id: true, name: true } } } }, history: { include: { user: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" as const } } };

const nested = (input: ActivityInput) => ({
  materials: { create: input.materials.map((m) => ({ name: m.name, productId: m.productId || null, quantity: new Prisma.Decimal(m.quantity), unit: m.unit, note: m.note || null })) },
  problems: { create: input.problems.map((p) => ({ description: p.description, note: p.note || null, priority: p.priority })) },
  attachments: { create: [...input.attachments, ...input.problems.flatMap((p) => p.attachments.map((a) => ({ ...a, kind: "PROBLEM_PHOTO" as const })))].map((a) => ({ ...a, mimeType: a.mimeType || null, size: a.size ?? null })) },
});

export async function list(q: any, organizationId: string, ownId?: string) {
  const where: Prisma.ActivityWhereInput = { organizationId, ...(ownId ? { employeeId: ownId } : {}), ...(q.employeeId ? { employeeId: q.employeeId } : {}), ...(q.sector ? { sector: { contains: q.sector, mode: "insensitive" } } : {}), ...(q.client ? { clientName: { contains: q.client, mode: "insensitive" } } : {}), ...(q.project ? { projectReference: { contains: q.project, mode: "insensitive" } } : {}), ...(q.service ? { service: { contains: q.service, mode: "insensitive" } } : {}), ...(q.status ? { status: q.status } : {}), ...((q.dateFrom || q.dateTo) ? { date: { gte: q.dateFrom, lte: q.dateTo } } : {}), ...(q.search ? { OR: [{ number: { contains: q.search, mode: "insensitive" } }, { service: { contains: q.search, mode: "insensitive" } }, { description: { contains: q.search, mode: "insensitive" } }, { clientName: { contains: q.search, mode: "insensitive" } }, { projectReference: { contains: q.search, mode: "insensitive" } }, { employee: { name: { contains: q.search, mode: "insensitive" } } }] } : {}) };
  const orderBy: Prisma.ActivityOrderByWithRelationInput = q.sort === "oldest" ? { date: "asc" } : q.sort === "employee" ? { employee: { name: "asc" } } : q.sort === "status" ? { status: "asc" } : { date: "desc" };
  const [items, total] = await prisma.$transaction([prisma.activity.findMany({ where, include: { employee: { select: { id: true, name: true, sector: true } }, _count: { select: { materials: true, problems: true, attachments: true } } }, orderBy, skip: (q.page - 1) * q.perPage, take: q.perPage }), prisma.activity.count({ where })]);
  return { items, meta: { page: q.page, perPage: q.perPage, total, pages: Math.max(1, Math.ceil(total / q.perPage)) } };
}

export async function get(id: string, organizationId: string) { const item = await prisma.activity.findFirst({ where: { id, organizationId }, include }); if (!item) throw new NotFoundError("Atividade não encontrada"); return item; }
export async function employees(organizationId: string) { return prisma.user.findMany({ where: { organizationId, status: "ACTIVE" }, select: { id: true, name: true, sector: true, position: true }, orderBy: { name: "asc" } }); }
export async function create(input: ActivityInput, actor: AuthUser) {
  const employeeId = input.employeeId || actor.id;
  const employee = await prisma.user.findFirst({ where: { id: employeeId, organizationId: actor.organizationId, status: "ACTIVE" }, select: { id: true } });
  if (!employee) throw new BadRequestError("Funcionário inválido para esta organização");
  const count = await prisma.activity.count({ where: { organizationId: actor.organizationId } });
  const number = `ATV-${String(count + 1).padStart(5, "0")}`;
  return prisma.$transaction(async (tx) => { const activity = await tx.activity.create({ data: { number, organizationId: actor.organizationId, employeeId: input.employeeId || actor.id, createdById: actor.id, sector: input.sector || actor.sector, date: input.date, startTime: input.startTime || null, endTime: input.endTime || null, clientName: input.clientName || null, projectReference: input.projectReference || null, service: input.service, description: input.description, problemsSummary: input.problemsSummary || null, observations: input.observations || null, signatureRequired: input.signatureRequired, status: input.status, agendaEventId: input.agendaEventId || null, taskId: input.taskId || null, assistanceId: input.assistanceId || null, completedAt: input.status === "COMPLETED" ? new Date() : null, ...nested(input), history: { create: { action: "CREATED", userId: actor.id, details: { status: input.status } } } }, include }); await tx.auditLog.create({ data: { action: "ACTIVITY_CREATED", entity: "Activity", entityId: activity.id, userId: actor.id, details: { number, organizationId: actor.organizationId } } }); return activity; });
}
export async function update(id: string, input: ActivityInput, actor: AuthUser) {
  const current = await get(id, actor.organizationId); const all = actor.permissions.includes("activities.edit.all");
  const employeeId = input.employeeId || current.employeeId;
  const employee = await prisma.user.findFirst({ where: { id: employeeId, organizationId: actor.organizationId, status: "ACTIVE" }, select: { id: true } });
  if (!employee) throw new BadRequestError("Funcionário inválido para esta organização");
  if (current.employeeId !== actor.id && !all) throw new ForbiddenError();
  if (["COMPLETED", "CANCELLED"].includes(current.status) && !all) throw new BadRequestError("Atividade concluída ou cancelada não pode ser editada");
  const events = [{ action: "EDITED", userId: actor.id, details: { materials: input.materials.length, problems: input.problems.length, attachments: input.attachments.length } }, ...(current.materials.length !== input.materials.length ? [{ action: "MATERIALS_CHANGED", userId: actor.id, details: { from: current.materials.length, to: input.materials.length } }] : []), ...(current.problems.length !== input.problems.length ? [{ action: "PROBLEMS_RECORDED", userId: actor.id, details: { from: current.problems.length, to: input.problems.length } }] : []), ...(current.attachments.length !== input.attachments.length ? [{ action: "ATTACHMENTS_CHANGED", userId: actor.id, details: { from: current.attachments.length, to: input.attachments.length } }] : [])];
  return prisma.$transaction(async (tx) => { await tx.activityMaterial.deleteMany({ where: { activityId: id } }); await tx.activityProblem.deleteMany({ where: { activityId: id } }); await tx.activityAttachment.deleteMany({ where: { activityId: id } }); await tx.activity.update({ where: { id }, data: { employeeId: input.employeeId || current.employeeId, sector: input.sector || null, date: input.date, startTime: input.startTime || null, endTime: input.endTime || null, clientName: input.clientName || null, projectReference: input.projectReference || null, service: input.service, description: input.description, problemsSummary: input.problemsSummary || null, observations: input.observations || null, signatureRequired: input.signatureRequired, agendaEventId: input.agendaEventId || null, taskId: input.taskId || null, assistanceId: input.assistanceId || null, ...nested(input), history: { create: events } } }); await tx.auditLog.create({ data: { action: "ACTIVITY_UPDATED", entity: "Activity", entityId: id, userId: actor.id } }); return tx.activity.findUniqueOrThrow({ where: { id }, include }); });
}
const transitions: Record<ActivityStatus, ActivityStatus[]> = { DRAFT: ["IN_PROGRESS", "CANCELLED"], IN_PROGRESS: ["COMPLETED", "CANCELLED"], COMPLETED: [], CANCELLED: [] };
export async function changeStatus(id: string, status: ActivityStatus, actor: AuthUser) { const current = await get(id, actor.organizationId); if (current.employeeId !== actor.id && !actor.permissions.includes("activities.edit.all")) throw new ForbiddenError(); if (!transitions[current.status].includes(status)) throw new BadRequestError("Transição de status inválida"); if (status === "COMPLETED" && !actor.permissions.includes("activities.complete")) throw new ForbiddenError(); if (status === "CANCELLED" && !actor.permissions.includes("activities.cancel")) throw new ForbiddenError(); return prisma.$transaction(async tx => { const result = await tx.activity.update({ where: { id }, data: { status, completedAt: status === "COMPLETED" ? new Date() : null, cancelledAt: status === "CANCELLED" ? new Date() : null, history: { create: { action: status === "COMPLETED" ? "COMPLETED" : "STATUS_CHANGED", userId: actor.id, details: { from: current.status, to: status } } } }, include }); await tx.auditLog.create({ data: { action: "ACTIVITY_STATUS_CHANGED", entity: "Activity", entityId: id, userId: actor.id, details: { from: current.status, to: status } } }); return result; }); }
export async function remove(id: string, actor: AuthUser) { const current = await get(id, actor.organizationId); if (current.status !== "DRAFT") throw new BadRequestError("Somente rascunhos podem ser excluídos"); if (current.employeeId !== actor.id && !actor.permissions.includes("activities.delete")) throw new ForbiddenError(); await prisma.$transaction([prisma.auditLog.create({ data: { action: "ACTIVITY_DELETED", entity: "Activity", entityId: id, userId: actor.id, details: { number: current.number } } }), prisma.activity.delete({ where: { id } })]); return { id }; }
export async function sign(id: string, input: any, actor: AuthUser) { await get(id, actor.organizationId); return prisma.$transaction(async tx => { const signature = await tx.activitySignature.upsert({ where: { activityId_role: { activityId: id, role: input.role } }, create: { activityId: id, ...input, signedById: actor.id }, update: { signerName: input.signerName, dataUrl: input.dataUrl, signedById: actor.id, signedAt: new Date() } }); await tx.activityHistory.create({ data: { activityId: id, userId: actor.id, action: "SIGNED", details: { role: input.role, signerName: input.signerName } } }); await tx.auditLog.create({ data: { action: "ACTIVITY_SIGNED", entity: "Activity", entityId: id, userId: actor.id, details: { role: input.role } } }); return signature; }); }
export async function indicators(organizationId: string, ownId?: string) { const where = { organizationId, ...(ownId ? { employeeId: ownId } : {}) }; const today = new Date(); today.setHours(0,0,0,0); const [todayCount, inProgress, completed, problems, rows] = await Promise.all([prisma.activity.count({ where: { ...where, date: today } }), prisma.activity.count({ where: { ...where, status: "IN_PROGRESS" } }), prisma.activity.count({ where: { ...where, status: "COMPLETED" } }), prisma.activity.count({ where: { ...where, problems: { some: {} } } }), prisma.activity.findMany({ where, select: { startTime: true, endTime: true, sector: true } })]); const hours = rows.reduce((sum, r) => { if (!r.startTime || !r.endTime) return sum; const [sh,sm]=r.startTime.split(":").map(Number), [eh,em]=r.endTime.split(":").map(Number); return sum + Math.max(0, (eh*60+em-sh*60-sm)/60); },0); const bySector = Object.entries(rows.reduce<Record<string,number>>((a,r)=>{const k=r.sector||"Sem setor";a[k]=(a[k]||0)+1;return a;},{})).map(([sector,total])=>({sector,total})); return { today: todayCount, inProgress, completed, withProblems: problems, hours: Math.round(hours*10)/10, bySector }; }
