CREATE TYPE "KanbanBoardVisibility" AS ENUM ('PRIVATE', 'TEAM', 'ORGANIZATION');
CREATE TYPE "KanbanBoardStatus" AS ENUM ('ACTIVE', 'ARCHIVED');
CREATE TYPE "KanbanTaskPriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');
CREATE TYPE "KanbanRecurrenceFrequency" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY');
CREATE TYPE "EnterpriseStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'INACTIVE');
CREATE TYPE "ClientStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE "ProjectStatus" AS ENUM ('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED');
CREATE TYPE "AssistanceStatus" AS ENUM ('OPEN', 'TRIAGE', 'SCHEDULED', 'IN_PROGRESS', 'WAITING_CLIENT', 'RESOLVED', 'CANCELLED');

CREATE TABLE "Enterprise" ("id" TEXT NOT NULL, "legalName" TEXT NOT NULL, "tradeName" TEXT, "document" TEXT, "slug" TEXT NOT NULL, "email" TEXT, "phone" TEXT, "status" "EnterpriseStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Enterprise_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Enterprise_document_key" ON "Enterprise"("document");
CREATE UNIQUE INDEX "Enterprise_slug_key" ON "Enterprise"("slug");
CREATE INDEX "Enterprise_status_idx" ON "Enterprise"("status");
INSERT INTO "Enterprise" ("id","legalName","tradeName","slug","updatedAt") VALUES ('default-enterprise','Gestium','Gestium','gestium',CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;
ALTER TABLE "Organization" ADD COLUMN "enterpriseId" TEXT;
UPDATE "Organization" SET "enterpriseId"='default-enterprise' WHERE "enterpriseId" IS NULL;
ALTER TABLE "Organization" ALTER COLUMN "enterpriseId" SET NOT NULL;
CREATE INDEX "Organization_enterpriseId_idx" ON "Organization"("enterpriseId");
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_enterpriseId_fkey" FOREIGN KEY ("enterpriseId") REFERENCES "Enterprise"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "Client" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "document" TEXT, "email" TEXT, "phone" TEXT, "address" TEXT, "notes" TEXT, "status" "ClientStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "organizationId" TEXT NOT NULL, CONSTRAINT "Client_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Project" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "status" "ProjectStatus" NOT NULL DEFAULT 'PLANNING', "startAt" TIMESTAMP(3), "dueAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "organizationId" TEXT NOT NULL, "clientId" TEXT NOT NULL, "managerId" TEXT, CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AssistanceTicket" ("id" TEXT NOT NULL, "number" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "status" "AssistanceStatus" NOT NULL DEFAULT 'OPEN', "priority" "KanbanTaskPriority" NOT NULL DEFAULT 'NORMAL', "dueAt" TIMESTAMP(3), "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "organizationId" TEXT NOT NULL, "clientId" TEXT NOT NULL, "projectId" TEXT, "assigneeId" TEXT, "createdById" TEXT NOT NULL, CONSTRAINT "AssistanceTicket_pkey" PRIMARY KEY ("id"));

CREATE TABLE "KanbanBoard" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "team" TEXT, "visibility" "KanbanBoardVisibility" NOT NULL DEFAULT 'TEAM', "status" "KanbanBoardStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "organizationId" TEXT NOT NULL, "ownerId" TEXT NOT NULL, "createdById" TEXT NOT NULL, CONSTRAINT "KanbanBoard_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanColumn" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "position" INTEGER NOT NULL, "cardLimit" INTEGER, "isInitial" BOOLEAN NOT NULL DEFAULT false, "isCompletion" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "boardId" TEXT NOT NULL, CONSTRAINT "KanbanColumn_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanTask" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "team" TEXT, "sector" TEXT, "priority" "KanbanTaskPriority" NOT NULL DEFAULT 'NORMAL', "startAt" TIMESTAMP(3), "dueAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "observations" TEXT, "position" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "columnId" TEXT NOT NULL, "assigneeId" TEXT, "createdById" TEXT NOT NULL, "requisitionId" TEXT, "agendaEventId" TEXT, "clientId" TEXT, "projectId" TEXT, "assistanceId" TEXT, CONSTRAINT "KanbanTask_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanTaskParticipant" ("taskId" TEXT NOT NULL, "userId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "KanbanTaskParticipant_pkey" PRIMARY KEY ("taskId","userId"));
CREATE TABLE "KanbanLabel" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "color" TEXT NOT NULL DEFAULT 'slate', "boardId" TEXT NOT NULL, "organizationId" TEXT NOT NULL, CONSTRAINT "KanbanLabel_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanTaskLabel" ("taskId" TEXT NOT NULL, "labelId" TEXT NOT NULL, CONSTRAINT "KanbanTaskLabel_pkey" PRIMARY KEY ("taskId","labelId"));
CREATE TABLE "KanbanChecklistItem" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "completed" BOOLEAN NOT NULL DEFAULT false, "position" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "taskId" TEXT NOT NULL, CONSTRAINT "KanbanChecklistItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanSubtask" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "completed" BOOLEAN NOT NULL DEFAULT false, "dueAt" TIMESTAMP(3), "observation" TEXT, "position" INTEGER NOT NULL, "taskId" TEXT NOT NULL, "assigneeId" TEXT, CONSTRAINT "KanbanSubtask_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanComment" ("id" TEXT NOT NULL, "body" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "taskId" TEXT NOT NULL, "authorId" TEXT NOT NULL, CONSTRAINT "KanbanComment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanAttachment" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "url" TEXT NOT NULL, "mimeType" TEXT, "size" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "taskId" TEXT NOT NULL, CONSTRAINT "KanbanAttachment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KanbanRecurrence" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "priority" "KanbanTaskPriority" NOT NULL DEFAULT 'NORMAL', "frequency" "KanbanRecurrenceFrequency" NOT NULL, "interval" INTEGER NOT NULL DEFAULT 1, "weekdays" INTEGER[], "nextRunAt" TIMESTAMP(3) NOT NULL, "endAt" TIMESTAMP(3), "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "organizationId" TEXT NOT NULL, "columnId" TEXT NOT NULL, "assigneeId" TEXT, "createdById" TEXT NOT NULL, CONSTRAINT "KanbanRecurrence_pkey" PRIMARY KEY ("id"));
ALTER TABLE "KanbanTask" ADD COLUMN "recurrenceId" TEXT, ADD COLUMN "occurrenceAt" TIMESTAMP(3);
CREATE TABLE "KanbanHistory" ("id" TEXT NOT NULL, "action" TEXT NOT NULL, "fromValue" JSONB, "toValue" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "taskId" TEXT NOT NULL, "userId" TEXT, CONSTRAINT "KanbanHistory_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "KanbanColumn_boardId_position_key" ON "KanbanColumn"("boardId", "position"); CREATE UNIQUE INDEX "KanbanLabel_boardId_name_key" ON "KanbanLabel"("boardId", "name");
CREATE UNIQUE INDEX "KanbanTask_recurrenceId_occurrenceAt_key" ON "KanbanTask"("recurrenceId", "occurrenceAt"); CREATE INDEX "KanbanTask_recurrenceId_idx" ON "KanbanTask"("recurrenceId"); CREATE INDEX "KanbanRecurrence_organizationId_active_nextRunAt_idx" ON "KanbanRecurrence"("organizationId", "active", "nextRunAt"); CREATE INDEX "KanbanRecurrence_columnId_idx" ON "KanbanRecurrence"("columnId"); CREATE INDEX "KanbanRecurrence_assigneeId_idx" ON "KanbanRecurrence"("assigneeId");
CREATE UNIQUE INDEX "Client_organizationId_document_key" ON "Client"("organizationId", "document"); CREATE UNIQUE INDEX "Project_organizationId_code_key" ON "Project"("organizationId", "code"); CREATE UNIQUE INDEX "AssistanceTicket_organizationId_number_key" ON "AssistanceTicket"("organizationId", "number");
CREATE INDEX "Client_organizationId_status_name_idx" ON "Client"("organizationId", "status", "name"); CREATE INDEX "Project_organizationId_status_idx" ON "Project"("organizationId", "status"); CREATE INDEX "Project_clientId_idx" ON "Project"("clientId"); CREATE INDEX "Project_managerId_idx" ON "Project"("managerId"); CREATE INDEX "AssistanceTicket_organizationId_status_priority_idx" ON "AssistanceTicket"("organizationId", "status", "priority"); CREATE INDEX "AssistanceTicket_clientId_idx" ON "AssistanceTicket"("clientId"); CREATE INDEX "AssistanceTicket_projectId_idx" ON "AssistanceTicket"("projectId"); CREATE INDEX "AssistanceTicket_assigneeId_idx" ON "AssistanceTicket"("assigneeId");
CREATE INDEX "KanbanBoard_organizationId_status_idx" ON "KanbanBoard"("organizationId", "status"); CREATE INDEX "KanbanBoard_ownerId_idx" ON "KanbanBoard"("ownerId"); CREATE INDEX "KanbanBoard_team_idx" ON "KanbanBoard"("team");
CREATE INDEX "KanbanColumn_boardId_idx" ON "KanbanColumn"("boardId"); CREATE INDEX "KanbanTask_columnId_position_idx" ON "KanbanTask"("columnId", "position"); CREATE INDEX "KanbanTask_assigneeId_dueAt_idx" ON "KanbanTask"("assigneeId", "dueAt"); CREATE INDEX "KanbanTask_requisitionId_idx" ON "KanbanTask"("requisitionId"); CREATE INDEX "KanbanTask_agendaEventId_idx" ON "KanbanTask"("agendaEventId"); CREATE INDEX "KanbanTask_dueAt_idx" ON "KanbanTask"("dueAt");
CREATE INDEX "KanbanTask_clientId_idx" ON "KanbanTask"("clientId"); CREATE INDEX "KanbanTask_projectId_idx" ON "KanbanTask"("projectId"); CREATE INDEX "KanbanTask_assistanceId_idx" ON "KanbanTask"("assistanceId");
CREATE INDEX "KanbanTaskParticipant_userId_idx" ON "KanbanTaskParticipant"("userId"); CREATE INDEX "KanbanLabel_organizationId_idx" ON "KanbanLabel"("organizationId"); CREATE INDEX "KanbanTaskLabel_labelId_idx" ON "KanbanTaskLabel"("labelId"); CREATE INDEX "KanbanChecklistItem_taskId_position_idx" ON "KanbanChecklistItem"("taskId", "position"); CREATE INDEX "KanbanSubtask_taskId_position_idx" ON "KanbanSubtask"("taskId", "position"); CREATE INDEX "KanbanSubtask_assigneeId_idx" ON "KanbanSubtask"("assigneeId"); CREATE INDEX "KanbanComment_taskId_createdAt_idx" ON "KanbanComment"("taskId", "createdAt"); CREATE INDEX "KanbanAttachment_taskId_idx" ON "KanbanAttachment"("taskId"); CREATE INDEX "KanbanHistory_taskId_createdAt_idx" ON "KanbanHistory"("taskId", "createdAt"); CREATE INDEX "KanbanHistory_userId_idx" ON "KanbanHistory"("userId");

ALTER TABLE "KanbanBoard" ADD CONSTRAINT "KanbanBoard_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanBoard" ADD CONSTRAINT "KanbanBoard_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "KanbanBoard" ADD CONSTRAINT "KanbanBoard_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Client" ADD CONSTRAINT "Client_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Project" ADD CONSTRAINT "Project_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Project" ADD CONSTRAINT "Project_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Project" ADD CONSTRAINT "Project_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "AssistanceTicket" ADD CONSTRAINT "AssistanceTicket_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AssistanceTicket" ADD CONSTRAINT "AssistanceTicket_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "AssistanceTicket" ADD CONSTRAINT "AssistanceTicket_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "AssistanceTicket" ADD CONSTRAINT "AssistanceTicket_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "AssistanceTicket" ADD CONSTRAINT "AssistanceTicket_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "KanbanColumn" ADD CONSTRAINT "KanbanColumn_boardId_fkey" FOREIGN KEY ("boardId") REFERENCES "KanbanBoard"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_columnId_fkey" FOREIGN KEY ("columnId") REFERENCES "KanbanColumn"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_requisitionId_fkey" FOREIGN KEY ("requisitionId") REFERENCES "Requisition"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_agendaEventId_fkey" FOREIGN KEY ("agendaEventId") REFERENCES "AgendaEvent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_assistanceId_fkey" FOREIGN KEY ("assistanceId") REFERENCES "AssistanceTicket"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "KanbanTask" ADD CONSTRAINT "KanbanTask_recurrenceId_fkey" FOREIGN KEY ("recurrenceId") REFERENCES "KanbanRecurrence"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "KanbanRecurrence" ADD CONSTRAINT "KanbanRecurrence_columnId_fkey" FOREIGN KEY ("columnId") REFERENCES "KanbanColumn"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanRecurrence" ADD CONSTRAINT "KanbanRecurrence_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "KanbanRecurrence" ADD CONSTRAINT "KanbanRecurrence_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "KanbanTaskParticipant" ADD CONSTRAINT "KanbanTaskParticipant_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanTaskParticipant" ADD CONSTRAINT "KanbanTaskParticipant_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KanbanLabel" ADD CONSTRAINT "KanbanLabel_boardId_fkey" FOREIGN KEY ("boardId") REFERENCES "KanbanBoard"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanLabel" ADD CONSTRAINT "KanbanLabel_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KanbanTaskLabel" ADD CONSTRAINT "KanbanTaskLabel_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanTaskLabel" ADD CONSTRAINT "KanbanTaskLabel_labelId_fkey" FOREIGN KEY ("labelId") REFERENCES "KanbanLabel"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KanbanChecklistItem" ADD CONSTRAINT "KanbanChecklistItem_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanSubtask" ADD CONSTRAINT "KanbanSubtask_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanSubtask" ADD CONSTRAINT "KanbanSubtask_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "KanbanComment" ADD CONSTRAINT "KanbanComment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanComment" ADD CONSTRAINT "KanbanComment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "KanbanAttachment" ADD CONSTRAINT "KanbanAttachment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanHistory" ADD CONSTRAINT "KanbanHistory_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "KanbanTask"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "KanbanHistory" ADD CONSTRAINT "KanbanHistory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "Permission" ("id","code","label","module","createdAt") VALUES
('perm_org_read','organization.read','Ver quadros e tarefas','Organização interna',CURRENT_TIMESTAMP),('perm_org_read_all','organization.read.all','Ver todos os quadros','Organização interna',CURRENT_TIMESTAMP),('perm_org_manage','organization.manage','Gerenciar quadros, colunas e etiquetas','Organização interna',CURRENT_TIMESTAMP),('perm_org_task_create','organization.tasks.create','Criar tarefas','Organização interna',CURRENT_TIMESTAMP),('perm_org_task_edit','organization.tasks.edit','Atualizar tarefas atribuídas','Organização interna',CURRENT_TIMESTAMP),('perm_org_task_edit_all','organization.tasks.edit.all','Atualizar todas as tarefas','Organização interna',CURRENT_TIMESTAMP),('perm_org_task_comment','organization.tasks.comment','Comentar em tarefas','Organização interna',CURRENT_TIMESTAMP) ON CONFLICT ("code") DO NOTHING;
INSERT INTO "RolePermission" ("roleId","permissionId") SELECT r."id",p."id" FROM "Role" r CROSS JOIN "Permission" p WHERE (r."name"='ADMIN' AND p."code" LIKE 'organization.%') OR (r."name"='MANAGER' AND p."code" LIKE 'organization.%') OR (r."name" IN ('WAREHOUSE','PRODUCTION') AND p."code" IN ('organization.read','organization.read.all','organization.tasks.create','organization.tasks.edit','organization.tasks.comment')) OR (r."name"='REQUESTER' AND p."code" IN ('organization.read','organization.tasks.create','organization.tasks.edit','organization.tasks.comment')) OR (r."name"='VIEWER' AND p."code"='organization.read') ON CONFLICT DO NOTHING;
