import { Router } from "express";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import { authenticate } from "../../middlewares/auth";
import { requireAnyPermission, requirePermission } from "../../middlewares/rbac";
import { asyncHandler } from "../../utils/asyncHandler";
import { BadRequestError, ForbiddenError, NotFoundError } from "../../utils/ApiError";
import { ok } from "../../utils/response";
import { prisma } from "../../prisma";
import type { AuthUser } from "../../types/express";
import { uploadAttachment } from "../../middlewares/upload";
import { attachmentInput, boardInput, columnInput, commentInput, itemInput, labelInput, moveInput, recurrenceInput, taskInput, taskUpdate } from "./organization.schema";

const router = Router();
router.use(authenticate);

const taskInclude = { assignee: { select: { id: true, name: true, sector: true } }, client: { select: { id: true, name: true } }, project: { select: { id: true, code: true, name: true } }, assistance: { select: { id: true, number: true, title: true } }, participants: { include: { user: { select: { id: true, name: true } } } }, labels: { include: { label: true } }, checklist: { orderBy: { position: "asc" as const } }, subtasks: { include: { assignee: { select: { id: true, name: true } } }, orderBy: { position: "asc" as const } }, comments: { include: { author: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" as const } }, attachments: true };

async function boardAccess(boardId: string, actor: AuthUser, edit = false) {
  const board = await prisma.kanbanBoard.findFirst({ where: { id: boardId, organizationId: actor.organizationId } });
  if (!board) throw new NotFoundError("Quadro não encontrado");
  const manager = actor.permissions.includes("organization.manage");
  const member = board.ownerId === actor.id || board.visibility === "ORGANIZATION" || (board.visibility === "TEAM" && !!board.team && board.team === actor.sector);
  if (!manager && (!member || (edit && board.ownerId !== actor.id))) throw new ForbiddenError("Você não tem acesso a este quadro");
  return board;
}

async function taskAccess(taskId: string, actor: AuthUser, edit = false) {
  const task = await prisma.kanbanTask.findUnique({ where: { id: taskId }, include: { column: { include: { board: true } } } });
  if (!task) throw new NotFoundError("Tarefa não encontrada");
  await boardAccess(task.column.boardId, actor);
  if (edit && !actor.permissions.includes("organization.tasks.edit.all") && task.assigneeId !== actor.id && task.createdById !== actor.id) throw new ForbiddenError("Você não pode alterar esta tarefa");
  return task;
}

async function history(taskId: string, userId: string, action: string, fromValue?: Prisma.InputJsonValue, toValue?: Prisma.InputJsonValue) {
  await prisma.kanbanHistory.create({ data: { taskId, userId, action, fromValue, toValue } });
}

async function validateLinks(input: { assigneeId?: string | null; participantIds?: string[]; labelIds?: string[]; clientId?: string | null; projectId?: string | null; assistanceId?: string | null; requisitionId?: string | null; agendaEventId?: string | null }, boardId: string, actor: AuthUser) {
  const userIds = [...new Set([input.assigneeId, ...(input.participantIds ?? [])].filter((id): id is string => !!id))];
  if (userIds.length && await prisma.user.count({ where: { id: { in: userIds }, organizationId: actor.organizationId, status: "ACTIVE" } }) !== userIds.length) throw new BadRequestError("Há responsáveis ou participantes inválidos");
  if (input.labelIds?.length && await prisma.kanbanLabel.count({ where: { id: { in: input.labelIds }, boardId } }) !== new Set(input.labelIds).size) throw new BadRequestError("Há etiquetas inválidas");
  const [client, project, assistance, requisition, agenda] = await Promise.all([
    input.clientId ? prisma.client.findFirst({ where: { id: input.clientId, organizationId: actor.organizationId } }) : null,
    input.projectId ? prisma.project.findFirst({ where: { id: input.projectId, organizationId: actor.organizationId } }) : null,
    input.assistanceId ? prisma.assistanceTicket.findFirst({ where: { id: input.assistanceId, organizationId: actor.organizationId } }) : null,
    input.requisitionId ? prisma.requisition.findUnique({ where: { id: input.requisitionId } }) : null,
    input.agendaEventId ? prisma.agendaEvent.findFirst({ where: { id: input.agendaEventId, organizationId: actor.organizationId } }) : null,
  ]);
  if (input.clientId && !client || input.projectId && !project || input.assistanceId && !assistance || input.requisitionId && !requisition || input.agendaEventId && !agenda) throw new BadRequestError("Um dos vínculos informados é inválido");
  if (project && input.clientId && project.clientId !== input.clientId) throw new BadRequestError("O projeto não pertence ao cliente");
  if (assistance && input.clientId && assistance.clientId !== input.clientId) throw new BadRequestError("A assistência não pertence ao cliente");
}

router.get("/boards", requirePermission("organization.read"), asyncHandler(async (req, res) => {
  const all = req.user!.permissions.includes("organization.read.all");
  const boards = await prisma.kanbanBoard.findMany({ where: { organizationId: req.user!.organizationId, status: req.query.archived === "true" ? "ARCHIVED" : "ACTIVE", ...(all ? {} : { OR: [{ ownerId: req.user!.id }, { visibility: "ORGANIZATION" }, { visibility: "TEAM", team: req.user!.sector ?? "__none__" }] }) }, include: { owner: { select: { id: true, name: true } }, _count: { select: { columns: true } } }, orderBy: { name: "asc" } });
  return ok(res, boards);
}));
router.get("/people", requirePermission("organization.read"), asyncHandler(async (req, res) => ok(res, await prisma.user.findMany({ where: { organizationId: req.user!.organizationId, status: "ACTIVE" }, select: { id: true, name: true, sector: true, position: true }, orderBy: { name: "asc" } }))));
router.get("/metrics", requirePermission("organization.read"), asyncHandler(async (req, res) => { const now = new Date(), week = new Date(now.getTime() + 7 * 86400000); const base = { column: { board: { organizationId: req.user!.organizationId, status: "ACTIVE" as const } } }; const own = { OR: [{ assigneeId: req.user!.id }, { participants: { some: { userId: req.user!.id } } }] }; const [mine, overdue, upcoming, urgent, completed] = await Promise.all([prisma.kanbanTask.count({ where: { ...base, ...own, completedAt: null } }), prisma.kanbanTask.count({ where: { ...base, ...(req.user!.permissions.includes("organization.read.all") ? {} : own), completedAt: null, dueAt: { lt: now } } }), prisma.kanbanTask.count({ where: { ...base, ...own, completedAt: null, dueAt: { gte: now, lte: week } } }), prisma.kanbanTask.count({ where: { ...base, ...(req.user!.permissions.includes("organization.read.all") ? {} : own), completedAt: null, priority: "URGENT" } }), prisma.kanbanTask.count({ where: { ...base, ...(req.user!.permissions.includes("organization.read.all") ? {} : own), completedAt: { gte: new Date(now.getTime() - 30 * 86400000) } } })]); return ok(res, { mine, overdue, upcoming, urgent, completed }); }));
router.get("/recurrences", requirePermission("organization.read"), asyncHandler(async (req, res) => ok(res, await prisma.kanbanRecurrence.findMany({ where: { organizationId: req.user!.organizationId, ...(req.query.boardId ? { column: { boardId: String(req.query.boardId) } } : {}) }, include: { assignee: { select: { id: true, name: true } }, column: { include: { board: { select: { id: true, name: true } } } } }, orderBy: { nextRunAt: "asc" } }))));
router.post("/recurrences", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const input = recurrenceInput.parse(req.body); const column = await prisma.kanbanColumn.findUnique({ where: { id: input.columnId } }); if (!column) throw new BadRequestError("Coluna inválida"); await boardAccess(column.boardId, req.user!, true); if (input.assigneeId && !await prisma.user.findFirst({ where: { id: input.assigneeId, organizationId: req.user!.organizationId } })) throw new BadRequestError("Responsável inválido"); return ok(res, await prisma.kanbanRecurrence.create({ data: { ...input, organizationId: req.user!.organizationId, createdById: req.user!.id } }), "Recorrência criada"); }));
router.patch("/recurrences/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const current = await prisma.kanbanRecurrence.findFirst({ where: { id: req.params.id, organizationId: req.user!.organizationId }, include: { column: true } }); if (!current) throw new NotFoundError("Recorrência não encontrada"); await boardAccess(current.column.boardId, req.user!, true); return ok(res, await prisma.kanbanRecurrence.update({ where: { id: current.id }, data: recurrenceInput.partial().parse(req.body) }), "Recorrência atualizada"); }));
router.post("/recurrences/process", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const now = new Date(); const due = await prisma.kanbanRecurrence.findMany({ where: { organizationId: req.user!.organizationId, active: true, nextRunAt: { lte: now }, OR: [{ endAt: null }, { endAt: { gte: now } }] } }); let created = 0; for (const recurrence of due) { const occurrenceAt = recurrence.nextRunAt; await prisma.$transaction(async tx => { const exists = await tx.kanbanTask.findFirst({ where: { recurrenceId: recurrence.id, occurrenceAt } }); if (!exists) { const position = await tx.kanbanTask.count({ where: { columnId: recurrence.columnId } }); await tx.kanbanTask.create({ data: { title: recurrence.title, description: recurrence.description, priority: recurrence.priority, columnId: recurrence.columnId, assigneeId: recurrence.assigneeId, createdById: recurrence.createdById, recurrenceId: recurrence.id, occurrenceAt, dueAt: occurrenceAt, position, history: { create: { action: "CREATED_BY_RECURRENCE", userId: req.user!.id } } } }); created++; } const next = nextOccurrence(occurrenceAt, recurrence.frequency, recurrence.interval, recurrence.weekdays); await tx.kanbanRecurrence.update({ where: { id: recurrence.id }, data: { nextRunAt: next, active: recurrence.endAt ? next <= recurrence.endAt : true } }); }); } return ok(res, { processed: due.length, created }, "Recorrências processadas"); }));
router.post("/deadlines/process", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const now = new Date(), soon = new Date(now.getTime() + 24 * 60 * 60 * 1000); const tasks = await prisma.kanbanTask.findMany({ where: { column: { board: { organizationId: req.user!.organizationId } }, completedAt: null, assigneeId: { not: null }, dueAt: { lte: soon } } }); let created = 0; for (const task of tasks) { const title = task.dueAt! < now ? "Tarefa atrasada" : "Prazo próximo"; const duplicate = await prisma.notification.findFirst({ where: { userId: task.assigneeId, title, message: task.title, createdAt: { gte: new Date(now.getTime() - 20 * 60 * 60 * 1000) } } }); if (!duplicate) { await prisma.notification.create({ data: { type: "INFO", title, message: task.title, userId: task.assigneeId } }); created++; } } return ok(res, { inspected: tasks.length, created }, "Prazos processados"); }));

router.post("/boards", requirePermission("organization.manage"), asyncHandler(async (req, res) => {
  const input = boardInput.parse(req.body); const ownerId = input.ownerId ?? req.user!.id;
  const owner = await prisma.user.findFirst({ where: { id: ownerId, organizationId: req.user!.organizationId } }); if (!owner) throw new BadRequestError("Responsável inválido");
  const board = await prisma.kanbanBoard.create({ data: { ...input, ownerId, organizationId: req.user!.organizationId, createdById: req.user!.id, columns: { create: [{ name: "A fazer", position: 0, isInitial: true }, { name: "Em andamento", position: 1 }, { name: "Concluído", position: 2, isCompletion: true }] } }, include: { columns: true } });
  await prisma.auditLog.create({ data: { action: "KANBAN_BOARD_CREATED", entity: "KanbanBoard", entityId: board.id, userId: req.user!.id, details: { name: board.name } } }); return ok(res, board, "Quadro criado");
}));

router.get("/boards/:id", requirePermission("organization.read"), asyncHandler(async (req, res) => {
  await boardAccess(req.params.id, req.user!); const board = await prisma.kanbanBoard.findUnique({ where: { id: req.params.id }, include: { owner: { select: { id: true, name: true } }, labels: true, columns: { orderBy: { position: "asc" }, include: { tasks: { include: taskInclude, orderBy: { position: "asc" } } } } } }); return ok(res, board);
}));

router.patch("/boards/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await boardAccess(req.params.id, req.user!, true); return ok(res, await prisma.kanbanBoard.update({ where: { id: req.params.id }, data: boardInput.partial().parse(req.body) }), "Quadro atualizado"); }));
router.post("/boards/:id/columns", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await boardAccess(req.params.id, req.user!, true); const input = columnInput.parse(req.body); const count = await prisma.kanbanColumn.count({ where: { boardId: req.params.id } }); if (input.isInitial) await prisma.kanbanColumn.updateMany({ where: { boardId: req.params.id }, data: { isInitial: false } }); if (input.isCompletion) await prisma.kanbanColumn.updateMany({ where: { boardId: req.params.id }, data: { isCompletion: false } }); return ok(res, await prisma.kanbanColumn.create({ data: { ...input, boardId: req.params.id, position: input.position ?? count } }), "Coluna criada"); }));
router.post("/boards/:id/columns/reorder", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await boardAccess(req.params.id, req.user!, true); const ids = z.array(z.string()).min(1).parse(req.body?.columnIds); const existing = await prisma.kanbanColumn.findMany({ where: { boardId: req.params.id }, select: { id: true } }); if (ids.length !== existing.length || ids.some(id => !existing.some(c => c.id === id))) throw new BadRequestError("A ordem deve conter todas as colunas do quadro"); await prisma.$transaction(async tx => { await tx.kanbanColumn.updateMany({ where: { boardId: req.params.id }, data: { position: { increment: 10000 } } }); for (let position = 0; position < ids.length; position++) await tx.kanbanColumn.update({ where: { id: ids[position] }, data: { position } }); }); return ok(res, null, "Colunas reordenadas"); }));
router.patch("/columns/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const col = await prisma.kanbanColumn.findUnique({ where: { id: req.params.id } }); if (!col) throw new NotFoundError(); await boardAccess(col.boardId, req.user!, true); const input = columnInput.partial().omit({ position: true }).parse(req.body); if (input.isInitial) await prisma.kanbanColumn.updateMany({ where: { boardId: col.boardId, id: { not: col.id } }, data: { isInitial: false } }); if (input.isCompletion) await prisma.kanbanColumn.updateMany({ where: { boardId: col.boardId, id: { not: col.id } }, data: { isCompletion: false } }); return ok(res, await prisma.kanbanColumn.update({ where: { id: col.id }, data: input }), "Coluna atualizada"); }));
router.delete("/columns/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const col = await prisma.kanbanColumn.findUnique({ where: { id: req.params.id }, include: { _count: { select: { tasks: true } } } }); if (!col) throw new NotFoundError(); await boardAccess(col.boardId, req.user!, true); if (col._count.tasks) throw new BadRequestError("Mova os cartões antes de excluir a coluna"); await prisma.kanbanColumn.delete({ where: { id: col.id } }); return ok(res, null, "Coluna excluída"); }));
router.post("/boards/:id/labels", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await boardAccess(req.params.id, req.user!, true); return ok(res, await prisma.kanbanLabel.create({ data: { ...labelInput.parse(req.body), boardId: req.params.id, organizationId: req.user!.organizationId } }), "Etiqueta criada"); }));
router.delete("/labels/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const label = await prisma.kanbanLabel.findUnique({ where: { id: req.params.id } }); if (!label) throw new NotFoundError(); await boardAccess(label.boardId, req.user!, true); await prisma.kanbanLabel.delete({ where: { id: label.id } }); return ok(res, null, "Etiqueta excluída"); }));

router.post("/tasks", requirePermission("organization.tasks.create"), asyncHandler(async (req, res) => { const input = taskInput.parse(req.body); const col = await prisma.kanbanColumn.findUnique({ where: { id: input.columnId }, include: { board: true, _count: { select: { tasks: true } } } }); if (!col) throw new BadRequestError("Coluna inválida"); await boardAccess(col.boardId, req.user!); await validateLinks(input, col.boardId, req.user!); if (col.cardLimit && col._count.tasks >= col.cardLimit) throw new BadRequestError("Limite de cartões atingido"); const { participantIds, labelIds, ...data } = input; const task = await prisma.kanbanTask.create({ data: { ...data, createdById: req.user!.id, position: col._count.tasks, participants: { create: participantIds.map(userId => ({ userId })) }, labels: { create: labelIds.map(labelId => ({ labelId })) }, history: { create: { action: "CREATED", userId: req.user!.id } } }, include: taskInclude }); if (task.assigneeId && task.assigneeId !== req.user!.id) await prisma.notification.create({ data: { type: "INFO", title: "Nova tarefa atribuída", message: task.title, userId: task.assigneeId } }); return ok(res, task, "Tarefa criada"); }));
router.get("/tasks/:id", requirePermission("organization.read"), asyncHandler(async (req, res) => { await taskAccess(req.params.id, req.user!); const task = await prisma.kanbanTask.findUnique({ where: { id: req.params.id }, include: { ...taskInclude, history: { include: { user: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" } }, column: { include: { board: { select: { id: true, name: true } } } }, requisition: { select: { id: true, number: true } }, agendaEvent: { select: { id: true, title: true, startAt: true } } } }); return ok(res, task); }));
router.patch("/tasks/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const current = await taskAccess(req.params.id, req.user!, true); const input = taskUpdate.parse(req.body); await validateLinks(input, current.column.boardId, req.user!); const { participantIds, labelIds, ...data } = input; const task = await prisma.$transaction(async tx => { if (participantIds) { await tx.kanbanTaskParticipant.deleteMany({ where: { taskId: current.id } }); await tx.kanbanTaskParticipant.createMany({ data: participantIds.map(userId => ({ taskId: current.id, userId })), skipDuplicates: true }); } if (labelIds) { await tx.kanbanTaskLabel.deleteMany({ where: { taskId: current.id } }); await tx.kanbanTaskLabel.createMany({ data: labelIds.map(labelId => ({ taskId: current.id, labelId })), skipDuplicates: true }); } return tx.kanbanTask.update({ where: { id: current.id }, data, include: taskInclude }); }); await history(current.id, req.user!.id, "UPDATED", { title: current.title, dueAt: current.dueAt?.toISOString() ?? null }, { title: task.title, dueAt: task.dueAt?.toISOString() ?? null }); return ok(res, task, "Tarefa atualizada"); }));
router.patch("/tasks/:id/move", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const current = await taskAccess(req.params.id, req.user!, true); const input = moveInput.parse(req.body); const target = await prisma.kanbanColumn.findUnique({ where: { id: input.columnId }, include: { board: true, _count: { select: { tasks: true } } } }); if (!target || target.boardId !== current.column.boardId) throw new BadRequestError("Coluna de destino inválida"); if (target.cardLimit && target._count.tasks >= target.cardLimit && target.id !== current.columnId) throw new BadRequestError("Limite de cartões atingido"); const position = Math.min(input.position, target.id === current.columnId ? Math.max(0, target._count.tasks - 1) : target._count.tasks); const task = await prisma.$transaction(async tx => { if (target.id !== current.columnId) { await tx.kanbanTask.updateMany({ where: { columnId: current.columnId, position: { gt: current.position } }, data: { position: { decrement: 1 } } }); await tx.kanbanTask.updateMany({ where: { columnId: target.id, position: { gte: position } }, data: { position: { increment: 1 } } }); } else if (position < current.position) await tx.kanbanTask.updateMany({ where: { columnId: target.id, position: { gte: position, lt: current.position } }, data: { position: { increment: 1 } } }); else if (position > current.position) await tx.kanbanTask.updateMany({ where: { columnId: target.id, position: { gt: current.position, lte: position } }, data: { position: { decrement: 1 } } }); return tx.kanbanTask.update({ where: { id: current.id }, data: { columnId: target.id, position, completedAt: target.isCompletion ? current.completedAt ?? new Date() : null }, include: taskInclude }); }); await history(task.id, req.user!.id, target.isCompletion ? "COMPLETED" : current.column.isCompletion ? "REOPENED" : "MOVED", { columnId: current.columnId, position: current.position }, { columnId: target.id, position }); if (task.assigneeId && task.assigneeId !== req.user!.id) await prisma.notification.create({ data: { type: "INFO", title: target.isCompletion ? "Tarefa concluída" : "Tarefa mudou de etapa", message: `${task.title} → ${target.name}`, userId: task.assigneeId } }); return ok(res, task, "Tarefa movida"); }));

router.get("/my-tasks", requirePermission("organization.read"), asyncHandler(async (req, res) => { const now = new Date(); const tasks = await prisma.kanbanTask.findMany({ where: { column: { board: { organizationId: req.user!.organizationId, status: "ACTIVE" } }, OR: [{ assigneeId: req.user!.id }, { participants: { some: { userId: req.user!.id } } }] }, include: { ...taskInclude, column: { include: { board: { select: { id: true, name: true } } } } }, orderBy: [{ dueAt: "asc" }, { priority: "desc" }] }); return ok(res, { overdue: tasks.filter(t => t.dueAt && t.dueAt < now && !t.completedAt), today: tasks.filter(t => t.dueAt?.toDateString() === now.toDateString() && !t.completedAt), upcoming: tasks.filter(t => t.dueAt && t.dueAt > now && t.dueAt.toDateString() !== now.toDateString() && !t.completedAt), completed: tasks.filter(t => t.completedAt).slice(0, 20) }); }));
router.post("/tasks/:id/comments", requirePermission("organization.tasks.comment"), asyncHandler(async (req, res) => { await taskAccess(req.params.id, req.user!); const comment = await prisma.kanbanComment.create({ data: { ...commentInput.parse(req.body), taskId: req.params.id, authorId: req.user!.id }, include: { author: { select: { id: true, name: true } } } }); await history(req.params.id, req.user!.id, "COMMENT_ADDED"); return ok(res, comment, "Comentário adicionado"); }));
router.post("/tasks/:id/checklist", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { await taskAccess(req.params.id, req.user!, true); const input = itemInput.pick({ title: true, position: true }).parse(req.body); const count = await prisma.kanbanChecklistItem.count({ where: { taskId: req.params.id } }); return ok(res, await prisma.kanbanChecklistItem.create({ data: { title: input.title, position: input.position ?? count, taskId: req.params.id } }), "Item criado"); }));
router.patch("/checklist/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const item = await prisma.kanbanChecklistItem.findUnique({ where: { id: req.params.id } }); if (!item) throw new NotFoundError(); await taskAccess(item.taskId, req.user!, true); const updated = await prisma.kanbanChecklistItem.update({ where: { id: item.id }, data: zChecklist(req.body) }); await history(item.taskId, req.user!.id, "CHECKLIST_UPDATED", { completed: item.completed }, { completed: updated.completed }); return ok(res, updated); }));
router.delete("/checklist/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const item = await prisma.kanbanChecklistItem.findUnique({ where: { id: req.params.id } }); if (!item) throw new NotFoundError(); await taskAccess(item.taskId, req.user!, true); await prisma.kanbanChecklistItem.delete({ where: { id: item.id } }); return ok(res, null, "Item excluído"); }));
router.post("/tasks/:id/subtasks", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { await taskAccess(req.params.id, req.user!, true); const input = itemInput.parse(req.body); if (input.assigneeId && !await prisma.user.findFirst({ where: { id: input.assigneeId, organizationId: req.user!.organizationId } })) throw new BadRequestError("Responsável inválido"); const count = await prisma.kanbanSubtask.count({ where: { taskId: req.params.id } }); return ok(res, await prisma.kanbanSubtask.create({ data: { ...input, position: input.position ?? count, taskId: req.params.id } }), "Subtarefa criada"); }));
router.patch("/subtasks/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const item = await prisma.kanbanSubtask.findUnique({ where: { id: req.params.id } }); if (!item) throw new NotFoundError(); await taskAccess(item.taskId, req.user!, true); const input = itemInput.partial().extend({ completed: zBoolean }).parse(req.body); const value = await prisma.kanbanSubtask.update({ where: { id: item.id }, data: input }); await history(item.taskId, req.user!.id, "SUBTASK_UPDATED"); return ok(res, value); }));
router.delete("/subtasks/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const item = await prisma.kanbanSubtask.findUnique({ where: { id: req.params.id } }); if (!item) throw new NotFoundError(); await taskAccess(item.taskId, req.user!, true); await prisma.kanbanSubtask.delete({ where: { id: item.id } }); return ok(res, null, "Subtarefa excluída"); }));
router.post("/tasks/:id/attachments", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { await taskAccess(req.params.id, req.user!, true); const attachment = await prisma.kanbanAttachment.create({ data: { ...attachmentInput.parse(req.body), taskId: req.params.id } }); await history(req.params.id, req.user!.id, "ATTACHMENT_ADDED"); return ok(res, attachment, "Arquivo anexado"); }));
router.delete("/attachments/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const file = await prisma.kanbanAttachment.findUnique({ where: { id: req.params.id } }); if (!file) throw new NotFoundError(); await taskAccess(file.taskId, req.user!, true); await prisma.kanbanAttachment.delete({ where: { id: file.id } }); await history(file.taskId, req.user!.id, "ATTACHMENT_REMOVED"); return ok(res, null, "Arquivo removido"); }));
router.post("/uploads", requirePermission("organization.tasks.create"), uploadAttachment.single("file"), asyncHandler(async (req, res) => { if (!req.file) throw new BadRequestError("Selecione um arquivo"); const baseUrl = `${req.protocol}://${req.get("host")}`; return ok(res, { name: req.file.originalname, url: `${baseUrl}/uploads/${req.file.filename}`, mimeType: req.file.mimetype, size: req.file.size }); }));
router.delete("/tasks/:id", requireAnyPermission(["organization.tasks.edit", "organization.tasks.edit.all"]), asyncHandler(async (req, res) => { const task = await taskAccess(req.params.id, req.user!, true); await prisma.$transaction([prisma.auditLog.create({ data: { action: "KANBAN_TASK_DELETED", entity: "KanbanTask", entityId: task.id, userId: req.user!.id, details: { title: task.title } } }), prisma.kanbanTask.delete({ where: { id: task.id } })]); return ok(res, null, "Tarefa excluída"); }));

function zChecklist(value: unknown) { const v = value as { title?: unknown; completed?: unknown; position?: unknown }; const data: { title?: string; completed?: boolean; position?: number } = {}; if (typeof v.title === "string") data.title = v.title.trim(); if (typeof v.completed === "boolean") data.completed = v.completed; if (typeof v.position === "number") data.position = v.position; return data; }
const zBoolean = z.boolean().optional();
function nextOccurrence(value: Date, frequency: "DAILY" | "WEEKLY" | "MONTHLY", interval: number, weekdays: number[]) { const next = new Date(value); if (frequency === "MONTHLY") next.setMonth(next.getMonth() + interval); else if (frequency === "WEEKLY" && weekdays.length) { do next.setDate(next.getDate() + 1); while (!weekdays.includes(next.getDay())); } else next.setDate(next.getDate() + (frequency === "WEEKLY" ? 7 : 1) * interval); return next; }

export default router;
