import { useMutation, useQuery } from "@tanstack/react-query";
import { FileText, Loader2, Paperclip, Plus, Sparkles, Trash2, UploadCloud } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ProductPicker } from "@/features/stock/product-picker";
import { useAuth } from "@/hooks/use-auth";
import { UNITS } from "@/lib/utils";
import { apiGet, apiPost, apiPut, apiUpload } from "@/services/api";
import type { Activity, ActivityAttachment, ActivityMaterial, ActivityProblem, ActivityStatus, Product, Unit } from "@/types";

type Form = { employeeId: string; sector: string; date: string; startTime: string; endTime: string; clientName: string; projectReference: string; service: string; description: string; problemsSummary: string; observations: string; signatureRequired: boolean; status: ActivityStatus; materials: ActivityMaterial[]; problems: ActivityProblem[]; attachments: ActivityAttachment[] };
const emptyMaterial = (): ActivityMaterial => ({ name: "", productId: null, quantity: 1, unit: "UNIT", note: "" });
const emptyProblem = (): ActivityProblem => ({ description: "", note: "", priority: "NORMAL", attachments: [] });
const today = () => new Date().toISOString().slice(0,10);

export function ActivityFormPage() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const { user, can } = useAuth();
  const [form, setForm] = useState<Form>(() => ({ employeeId: user?.id ?? "", sector: user?.sector ?? "", date: today(), startTime: "", endTime: "", clientName: "", projectReference: "", service: "", description: "", problemsSummary: "", observations: "", signatureRequired: false, status: "DRAFT", materials: [], problems: [], attachments: [] }));
  const [loadedId, setLoadedId] = useState<string | null>(null); const [pickerIndex, setPickerIndex] = useState<number | null>(null); const [aiOpen, setAiOpen] = useState(false); const [aiText, setAiText] = useState(""); const [uploading, setUploading] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const detail = useQuery({ queryKey: ["activity", id], enabled: editing, queryFn: ()=>apiGet<{data:Activity}>(`/activities/${id}`) });
  useEffect(() => { const a=detail.data?.data; if(!a||loadedId===a.id)return; setLoadedId(a.id); setForm({ employeeId:a.employeeId, sector:a.sector||"", date:a.date.slice(0,10), startTime:a.startTime||"", endTime:a.endTime||"", clientName:a.clientName||"", projectReference:a.projectReference||"", service:a.service, description:a.description, problemsSummary:a.problemsSummary||"", observations:a.observations||"", signatureRequired:a.signatureRequired, status:a.status, materials:a.materials.map(m=>({...m,quantity:Number(m.quantity)})), problems:a.problems.map(p=>({...p,attachments:p.attachments||[]})), attachments:a.attachments }); }, [detail.data?.data, loadedId]);
  const users = useQuery({ queryKey:["activity-users"], enabled:can("activities.read.all"), queryFn:()=>apiGet<{data:{id:string;name:string;sector:string|null}[]}>("/activities/employees") });
  const save = useMutation({ mutationFn:()=>editing?apiPut<{data:Activity}>(`/activities/${id}`,form):apiPost<{data:Activity}>("/activities",form), onSuccess:(r)=>{toast.success(editing?"Atividade atualizada":"Atividade criada");navigate(`/atividades/${r.data.id}`);}, onError:(e)=>toast.error((e as Error).message) });
  const ai = useMutation({ mutationFn:()=>apiPost<{data:Partial<Form>}>("/activities/ai-suggest",{text:aiText}), onSuccess:(r)=>{const s=r.data;setForm(f=>({...f,service:s.service||f.service,description:s.description||f.description,startTime:s.startTime||f.startTime,endTime:s.endTime||f.endTime,materials:s.materials?.length?s.materials:f.materials,problems:s.problems?.length?s.problems:f.problems,observations:s.observations||f.observations}));setAiOpen(false);toast.success("Sugestões preenchidas. Revise antes de salvar.");},onError:(e)=>toast.error((e as Error).message)});
  const patch = <K extends keyof Form>(key:K,value:Form[K])=>setForm(f=>({...f,[key]:value}));
  const upload = async(files:FileList)=>{setUploading(true);try{const results=await Promise.all(Array.from(files).map(file=>apiUpload<{data:ActivityAttachment}>("/activities/attachments",file)));patch("attachments",[...form.attachments,...results.map(r=>r.data)]);toast.success("Arquivos anexados");}catch(e){toast.error((e as Error).message)}finally{setUploading(false);if(fileRef.current)fileRef.current.value="";}};
  if (editing && detail.isLoading) return <div className="p-8 text-sm text-muted-foreground">Carregando atividade...</div>;
  return <div className="space-y-6">
    <PageHeader title={editing?"Editar atividade":"Novo relatório de atividade"} description="Registre o serviço realizado. Cliente e projeto são opcionais para atividades internas."><Button variant="outline" onClick={()=>navigate(editing?`/atividades/${id}`:"/atividades")}>Cancelar</Button><Button variant="outline" onClick={()=>setAiOpen(true)}><Sparkles className="h-4 w-4" />Preencher com IA</Button></PageHeader>
    <Card><CardHeader><CardTitle>Informações gerais</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <div><Label>Funcionário *</Label>{can("activities.read.all")?<Select value={form.employeeId} onValueChange={v=>patch("employeeId",v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{users.data?.data.map(u=><SelectItem key={u.id} value={u.id}>{u.name}</SelectItem>)}</SelectContent></Select>:<Input value={user?.name||""} disabled />}</div>
      <div><Label>Setor</Label><Input value={form.sector} onChange={e=>patch("sector",e.target.value)} /></div><div><Label>Data *</Label><Input type="date" value={form.date} onChange={e=>patch("date",e.target.value)} /></div><div><Label>Status inicial</Label><Select value={form.status} onValueChange={v=>patch("status",v as ActivityStatus)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="DRAFT">Rascunho</SelectItem><SelectItem value="IN_PROGRESS">Em andamento</SelectItem></SelectContent></Select></div>
      <div><Label>Horário de início</Label><Input type="time" value={form.startTime} onChange={e=>patch("startTime",e.target.value)} /></div><div><Label>Horário de término</Label><Input type="time" value={form.endTime} onChange={e=>patch("endTime",e.target.value)} /></div><div><Label>Cliente (opcional)</Label><Input value={form.clientName} onChange={e=>patch("clientName",e.target.value)} /></div><div><Label>Projeto (opcional)</Label><Input value={form.projectReference} onChange={e=>patch("projectReference",e.target.value)} /></div>
      <div className="md:col-span-2"><Label>Serviço realizado *</Label><Input value={form.service} onChange={e=>patch("service",e.target.value)} /></div><div className="md:col-span-2"><Label>Assinatura necessária</Label><label className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.signatureRequired} onChange={e=>patch("signatureRequired",e.target.checked)} />Solicitar assinatura ao concluir</label></div>
      <div className="md:col-span-2 xl:col-span-4"><Label>Descrição *</Label><Textarea rows={5} value={form.description} onChange={e=>patch("description",e.target.value)} /></div><div className="md:col-span-2"><Label>Problemas encontrados (resumo)</Label><Textarea value={form.problemsSummary} onChange={e=>patch("problemsSummary",e.target.value)} /></div><div className="md:col-span-2"><Label>Observações</Label><Textarea value={form.observations} onChange={e=>patch("observations",e.target.value)} /></div>
    </CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Materiais utilizados</CardTitle><Button size="sm" variant="outline" onClick={()=>patch("materials",[...form.materials,emptyMaterial()])}><Plus className="h-4 w-4" />Material</Button></CardHeader><CardContent className="space-y-3">{form.materials.length===0?<p className="text-sm text-muted-foreground">Nenhum material informado. O estoque não será baixado automaticamente.</p>:form.materials.map((m,i)=><div key={i} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[2fr_100px_150px_2fr_auto]"><Button variant="outline" className="justify-start" onClick={()=>setPickerIndex(i)}>{m.name||"Associar produto/material"}</Button><Input type="number" min="0.001" step="0.001" value={m.quantity} onChange={e=>patch("materials",form.materials.map((x,j)=>j===i?{...x,quantity:Number(e.target.value)}:x))}/><Select value={m.unit} onValueChange={v=>patch("materials",form.materials.map((x,j)=>j===i?{...x,unit:v as Unit}:x))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(UNITS).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select><Input placeholder="Observação" value={m.note||""} onChange={e=>patch("materials",form.materials.map((x,j)=>j===i?{...x,note:e.target.value}:x))}/><Button size="icon" variant="ghost" onClick={()=>patch("materials",form.materials.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Problemas identificados</CardTitle><Button size="sm" variant="outline" onClick={()=>patch("problems",[...form.problems,emptyProblem()])}><Plus className="h-4 w-4" />Problema</Button></CardHeader><CardContent className="space-y-3">{form.problems.map((p,i)=><div key={i} className="grid gap-3 rounded-lg border p-3 md:grid-cols-4"><div className="md:col-span-2"><Label>Descrição</Label><Input value={p.description} onChange={e=>patch("problems",form.problems.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></div><div><Label>Prioridade</Label><Select value={p.priority} onValueChange={v=>patch("problems",form.problems.map((x,j)=>j===i?{...x,priority:v as ActivityProblem["priority"]}:x))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="LOW">Baixa</SelectItem><SelectItem value="NORMAL">Normal</SelectItem><SelectItem value="HIGH">Alta</SelectItem><SelectItem value="URGENT">Urgente</SelectItem></SelectContent></Select></div><Button size="icon" variant="ghost" className="self-end" onClick={()=>patch("problems",form.problems.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4" /></Button><div className="md:col-span-4"><Label>Observação</Label><Textarea value={p.note||""} onChange={e=>patch("problems",form.problems.map((x,j)=>j===i?{...x,note:e.target.value}:x))}/></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Paperclip className="h-5 w-5" />Fotos e arquivos</CardTitle></CardHeader><CardContent className="space-y-3"><input ref={fileRef} className="sr-only" type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt" onChange={e=>e.target.files&&void upload(e.target.files)}/><button type="button" className="flex w-full flex-col items-center rounded-lg border-2 border-dashed p-8 hover:bg-muted/30" onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files)}}>{uploading?<Loader2 className="h-8 w-8 animate-spin text-primary"/>:<UploadCloud className="h-8 w-8 text-primary"/>}<strong className="mt-2">Arraste fotos e arquivos ou clique para procurar</strong><span className="text-xs text-muted-foreground">Até 10 MB por arquivo</span></button>{form.attachments.map((a,i)=><div key={a.url} className="flex items-center gap-3 rounded-md border p-3"><FileText className="h-5 w-5"/><span className="min-w-0 flex-1 truncate text-sm">{a.name}</span><Button size="icon" variant="ghost" onClick={()=>patch("attachments",form.attachments.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></Button></div>)}</CardContent></Card>
    <div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>navigate("/atividades")}>Cancelar</Button><Button disabled={save.isPending||form.service.trim().length<2||form.description.trim().length<2} onClick={()=>save.mutate()}>{save.isPending&&<Loader2 className="h-4 w-4 animate-spin"/>}{editing?"Salvar alterações":"Salvar relatório"}</Button></div>
    <Dialog open={aiOpen} onOpenChange={setAiOpen}><DialogContent><DialogHeader><DialogTitle>✨ Preencher com IA</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Descreva somente o que aconteceu. A sugestão preencherá o formulário, mas não salvará nada automaticamente.</p><Textarea rows={8} placeholder="Ex.: Fiz a instalação..." value={aiText} onChange={e=>setAiText(e.target.value)}/><DialogFooter><Button variant="outline" onClick={()=>setAiOpen(false)}>Cancelar</Button><Button disabled={ai.isPending||aiText.trim().length<10} onClick={()=>ai.mutate()}>{ai.isPending&&<Loader2 className="h-4 w-4 animate-spin"/>}Interpretar e preencher</Button></DialogFooter></DialogContent></Dialog>
    <ProductPicker open={pickerIndex!==null} onOpenChange={open=>!open&&setPickerIndex(null)} onSelect={(product:Product)=>{if(pickerIndex!==null)patch("materials",form.materials.map((m,i)=>i===pickerIndex?{...m,name:product.name,productId:product.id,product,unit:product.unit}:m));setPickerIndex(null);}}/>
  </div>;
}
