import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Clock3, FileClock, Plus, Search, Timer } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { PageHeader } from "@/components/page-header";
import { KpiCard } from "@/components/kpi-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Pagination } from "@/components/ui/pagination";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { EmptyState, TableSkeleton } from "@/components/ui/states";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useAuth } from "@/hooks/use-auth";
import { apiGet } from "@/services/api";
import type { Activity, ActivityStatus, Paginated } from "@/types";

const statusLabel: Record<ActivityStatus, string> = { DRAFT: "Rascunho", IN_PROGRESS: "Em andamento", COMPLETED: "Concluído", CANCELLED: "Cancelado" };
const statusVariant: Record<ActivityStatus, "muted" | "warning" | "success" | "danger"> = { DRAFT: "muted", IN_PROGRESS: "warning", COMPLETED: "success", CANCELLED: "danger" };

export function ActivitiesPage() {
  const { can } = useAuth(); const navigate = useNavigate();
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [employeeId, setEmployeeId] = useState("ALL"); const [sector, setSector] = useState(""); const [client, setClient] = useState(""); const [project, setProject] = useState(""); const [service, setService] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [sort, setSort] = useState("newest"); const [my, setMy] = useState(false);
  const params = { page, perPage: 15, search: search || undefined, status: status === "ALL" ? undefined : status, employeeId: employeeId === "ALL" ? undefined : employeeId, sector: sector || undefined, client: client || undefined, project: project || undefined, service: service || undefined, dateFrom: dateFrom || undefined, dateTo: dateTo || undefined, sort, my: my ? "true" : undefined };
  const query = useQuery({ queryKey: ["activities", params], queryFn: () => apiGet<Paginated<Activity[]>>("/activities", params) });
  const indicators = useQuery({ queryKey: ["activity-indicators"], queryFn: () => apiGet<{ data: { today: number; inProgress: number; completed: number; withProblems: number; hours: number; bySector: { sector: string; total: number }[] } }>("/activities/indicators") });
  const employees = useQuery({ queryKey: ["activity-employees"], enabled: can("activities.read.all"), queryFn: () => apiGet<{ data: { id: string; name: string }[] }>("/activities/employees") });
  const metrics = indicators.data?.data; const rows = query.data?.data ?? [];
  return <div className="space-y-6">
    <PageHeader title="Atividades" description="Relatórios digitais de serviços, materiais, problemas e assinaturas.">{can("activities.create") && <Button onClick={() => navigate("/atividades/nova")}><Plus className="h-4 w-4" />Novo relatório</Button>}</PageHeader>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><KpiCard title="Hoje" value={metrics?.today ?? 0} icon={FileClock} /><KpiCard title="Em andamento" value={metrics?.inProgress ?? 0} icon={Clock3} /><KpiCard title="Concluídas" value={metrics?.completed ?? 0} icon={CheckCircle2} /><KpiCard title="Com problemas" value={metrics?.withProblems ?? 0} icon={AlertTriangle} /><KpiCard title="Horas registradas" value={metrics?.hours ?? 0} icon={Timer} /></div>
    {metrics?.bySector?.length ? <Card><CardHeader><CardTitle className="text-base">Atividades por setor</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{metrics.bySector.map((item) => <Badge key={item.sector} variant="secondary">{item.sector}: {item.total}</Badge>)}</CardContent></Card> : null}
    <Card><CardContent className="grid gap-3 pt-6 md:grid-cols-2 xl:grid-cols-5"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Número, funcionário, serviço..." value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></div><Select value={status} onValueChange={(v) => { setStatus(v); setPage(1); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Todos os status</SelectItem>{Object.entries(statusLabel).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>{can("activities.read.all")&&<Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="Funcionário" /></SelectTrigger><SelectContent><SelectItem value="ALL">Todos os funcionários</SelectItem>{employees.data?.data.map(e=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select>}<Input placeholder="Setor" value={sector} onChange={(e)=>setSector(e.target.value)} /><Select value={sort} onValueChange={setSort}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="newest">Mais recentes</SelectItem><SelectItem value="oldest">Mais antigas</SelectItem><SelectItem value="employee">Funcionário</SelectItem><SelectItem value="status">Status</SelectItem></SelectContent></Select><Input placeholder="Cliente" value={client} onChange={(e)=>setClient(e.target.value)} /><Input placeholder="Projeto" value={project} onChange={(e)=>setProject(e.target.value)} /><Input placeholder="Serviço" value={service} onChange={(e)=>setService(e.target.value)} /><Input type="date" aria-label="Data inicial" value={dateFrom} onChange={(e)=>setDateFrom(e.target.value)} /><Input type="date" aria-label="Data final" value={dateTo} onChange={(e)=>setDateTo(e.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={my} onChange={(e)=>setMy(e.target.checked)} />Somente minhas atividades</label></CardContent></Card>
    <Card><CardContent className="p-0">{query.isLoading ? <div className="p-4"><TableSkeleton rows={7} /></div> : rows.length === 0 ? <EmptyState icon={FileClock} title="Nenhuma atividade encontrada" description="Crie um relatório ou ajuste os filtros." /> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Número</TableHead><TableHead>Data</TableHead><TableHead>Funcionário / setor</TableHead><TableHead>Serviço</TableHead><TableHead>Cliente / projeto</TableHead><TableHead>Status</TableHead><TableHead>Horário</TableHead></TableRow></TableHeader><TableBody>{rows.map((a)=><TableRow key={a.id} className="cursor-pointer" onClick={()=>navigate(`/atividades/${a.id}`)}><TableCell className="font-semibold">{a.number}</TableCell><TableCell>{new Date(a.date).toLocaleDateString("pt-BR",{timeZone:"UTC"})}</TableCell><TableCell>{a.employee.name}<span className="block text-xs text-muted-foreground">{a.sector || "Sem setor"}</span></TableCell><TableCell className="max-w-[240px] truncate">{a.service}</TableCell><TableCell>{a.clientName || "Atividade interna"}<span className="block text-xs text-muted-foreground">{a.projectReference || "Sem projeto"}</span></TableCell><TableCell><Badge variant={statusVariant[a.status]}>{statusLabel[a.status]}</Badge></TableCell><TableCell>{a.startTime && a.endTime ? `${a.startTime}–${a.endTime}` : "—"}</TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    {query.data?.meta && <Pagination {...query.data.meta} onChange={setPage} />}
  </div>;
}
