import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, Download, Edit, FileText, Loader2, PenLine, Play, Printer, Trash2, XCircle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { EmptyState, TableSkeleton } from "@/components/ui/states";
import { useAuth } from "@/hooks/use-auth";
import { UNITS } from "@/lib/utils";
import { apiDelete, apiGet, apiPatch, apiPost, getToken } from "@/services/api";
import type { Activity, ActivityStatus } from "@/types";

const labels:Record<ActivityStatus,string>={DRAFT:"Rascunho",IN_PROGRESS:"Em andamento",COMPLETED:"Concluído",CANCELLED:"Cancelado"};
const historyLabels:Record<string,string>={CREATED:"Relatório criado",EDITED:"Relatório editado",STATUS_CHANGED:"Status alterado",COMPLETED:"Atividade concluída",SIGNED:"Assinatura registrada",MATERIALS_CHANGED:"Materiais adicionados ou removidos",PROBLEMS_RECORDED:"Problemas atualizados",ATTACHMENTS_CHANGED:"Arquivos adicionados ou removidos"};

function SignatureDialog({open,onOpenChange,onSave,pending}:{open:boolean;onOpenChange:(v:boolean)=>void;onSave:(v:{role:string;signerName:string;dataUrl:string})=>void;pending:boolean}) {
  const canvasRef=useRef<HTMLCanvasElement>(null); const drawing=useRef(false); const [name,setName]=useState(""); const [role,setRole]=useState("EMPLOYEE"); const [hasInk,setHasInk]=useState(false);
  useEffect(()=>{if(!open)return;const c=canvasRef.current;if(!c)return;const ratio=window.devicePixelRatio||1;c.width=c.clientWidth*ratio;c.height=160*ratio;const ctx=c.getContext("2d");ctx?.scale(ratio,ratio);if(ctx){ctx.lineWidth=2;ctx.lineCap="round";ctx.strokeStyle="#111827";}setHasInk(false);},[open]);
  const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Assinatura digital</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Assinante</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Tipo</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={role} onChange={e=>setRole(e.target.value)}><option value="EMPLOYEE">Funcionário</option><option value="CLIENT">Cliente</option><option value="INSPECTOR">Responsável pela conferência</option></select></div><div><Label>Assine no campo abaixo</Label><canvas ref={canvasRef} className="mt-1 h-40 w-full touch-none rounded-md border bg-white" onPointerDown={e=>{drawing.current=true;const p=point(e);const ctx=e.currentTarget.getContext("2d");ctx?.beginPath();ctx?.moveTo(p.x,p.y);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drawing.current)return;const p=point(e);const ctx=e.currentTarget.getContext("2d");ctx?.lineTo(p.x,p.y);ctx?.stroke();setHasInk(true)}} onPointerUp={()=>drawing.current=false}/></div><Button variant="ghost" size="sm" onClick={()=>{const c=canvasRef.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);setHasInk(false)}}>Limpar assinatura</Button></div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button disabled={pending||name.trim().length<2||!hasInk} onClick={()=>{const dataUrl=canvasRef.current?.toDataURL("image/png");if(dataUrl)onSave({role,signerName:name,dataUrl})}}>Confirmar assinatura</Button></DialogFooter></DialogContent></Dialog>;
}

export function ActivityDetailPage(){
  const {id}=useParams();const navigate=useNavigate();const {can}=useAuth();const qc=useQueryClient();const [signOpen,setSignOpen]=useState(false);
  const query=useQuery({queryKey:["activity",id],queryFn:()=>apiGet<{data:Activity}>(`/activities/${id}`)});const a=query.data?.data;
  const status=useMutation({mutationFn:(s:ActivityStatus)=>apiPatch(`/activities/${id}/status`,{status:s}),onSuccess:()=>{toast.success("Status atualizado");void qc.invalidateQueries({queryKey:["activity",id]});void qc.invalidateQueries({queryKey:["activities"]});},onError:e=>toast.error((e as Error).message)});
  const remove=useMutation({mutationFn:()=>apiDelete(`/activities/${id}`),onSuccess:()=>{toast.success("Atividade excluída");navigate("/atividades")},onError:e=>toast.error((e as Error).message)});
  const sign=useMutation({mutationFn:(v:{role:string;signerName:string;dataUrl:string})=>apiPost(`/activities/${id}/signatures`,v),onSuccess:()=>{toast.success("Assinatura registrada");setSignOpen(false);void qc.invalidateQueries({queryKey:["activity",id]})},onError:e=>toast.error((e as Error).message)});
  const openPdf=async(print=false)=>{try{const res=await fetch(`/api/activities/${id}/pdf`,{headers:{Authorization:`Bearer ${getToken()}`}});if(!res.ok)throw new Error("Não foi possível gerar o PDF");const url=URL.createObjectURL(await res.blob());const win=window.open(url,"_blank");if(print&&win)win.addEventListener("load",()=>win.print());setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){toast.error((e as Error).message)}};
  if(query.isLoading)return <TableSkeleton rows={8}/>;if(!a)return <EmptyState title="Atividade não encontrada"/>;
  const canEdit=can("activities.edit")||can("activities.edit.all");
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Button size="icon" variant="outline" onClick={()=>navigate("/atividades")}><ArrowLeft className="h-4 w-4"/></Button><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">{a.number}</h1><Badge>{labels[a.status]}</Badge></div><p className="text-sm text-muted-foreground">{a.service}</p></div></div><div className="flex flex-wrap gap-2">{a.status==="DRAFT"&&canEdit&&<Button variant="outline" onClick={()=>navigate(`/atividades/${id}/editar`)}><Edit className="h-4 w-4"/>Editar</Button>}{a.status==="DRAFT"&&can("activities.complete")&&<Button onClick={()=>status.mutate("IN_PROGRESS")}><Play className="h-4 w-4"/>Iniciar</Button>}{a.status==="IN_PROGRESS"&&can("activities.complete")&&<Button onClick={()=>status.mutate("COMPLETED")}><CheckCircle2 className="h-4 w-4"/>Concluir</Button>}{!["COMPLETED","CANCELLED"].includes(a.status)&&can("activities.cancel")&&<Button variant="destructive" onClick={()=>status.mutate("CANCELLED")}><XCircle className="h-4 w-4"/>Cancelar</Button>}{a.status==="DRAFT"&&canEdit&&<Button variant="ghost" onClick={()=>confirm("Excluir este rascunho?")&&remove.mutate()}><Trash2 className="h-4 w-4"/></Button>}{can("activities.sign")&&<Button variant="outline" onClick={()=>setSignOpen(true)}><PenLine className="h-4 w-4"/>Assinar</Button>}{can("activities.export")&&<><Button variant="outline" onClick={()=>void openPdf()}><Download className="h-4 w-4"/>PDF</Button><Button variant="outline" onClick={()=>void openPdf(true)}><Printer className="h-4 w-4"/>Imprimir</Button></>}</div></div>
  <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Relatório</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Info label="Funcionário" value={a.employee.name}/><Info label="Setor" value={a.sector}/><Info label="Data" value={new Date(a.date).toLocaleDateString("pt-BR",{timeZone:"UTC"})}/><Info label="Horário" value={a.startTime&&a.endTime?`${a.startTime} às ${a.endTime}`:a.startTime}/><Info label="Cliente" value={a.clientName||"Atividade interna"}/><Info label="Projeto" value={a.projectReference}/><div className="sm:col-span-2"><Info label="Serviço realizado" value={a.service}/></div><div className="sm:col-span-2"><Info label="Descrição" value={a.description}/></div>{a.problemsSummary&&<div className="sm:col-span-2"><Info label="Problemas encontrados" value={a.problemsSummary}/></div>}{a.observations&&<div className="sm:col-span-2"><Info label="Observações" value={a.observations}/></div>}</CardContent></Card><Card><CardHeader><CardTitle>Resumo</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><strong>{a.materials.length}</strong> materiais utilizados</p><p><strong>{a.problems.length}</strong> problemas registrados</p><p><strong>{a.attachments.length}</strong> anexos</p><p><strong>{a.signatures.length}</strong> assinaturas</p><p className="text-muted-foreground">Nenhuma baixa de estoque foi realizada.</p></CardContent></Card></div>
  {a.materials.length>0&&<Card><CardHeader><CardTitle>Materiais utilizados</CardTitle></CardHeader><CardContent className="space-y-2">{a.materials.map(m=><div key={m.id} className="flex flex-wrap justify-between gap-2 rounded-md border p-3"><div><strong>{m.name}</strong>{m.product&&<p className="text-xs text-muted-foreground">Produto {m.product.code}</p>}</div><span>{Number(m.quantity)} {UNITS[m.unit]||m.unit}{m.note?` • ${m.note}`:""}</span></div>)}</CardContent></Card>}
  {a.problems.length>0&&<Card><CardHeader><CardTitle>Problemas encontrados</CardTitle></CardHeader><CardContent className="space-y-3">{a.problems.map(p=><div key={p.id} className="rounded-md border-l-4 border-l-amber-500 bg-muted/20 p-4"><div className="flex justify-between gap-2"><strong>{p.description}</strong><Badge variant={p.priority==="URGENT"||p.priority==="HIGH"?"danger":"secondary"}>{p.priority}</Badge></div>{p.note&&<p className="mt-2 text-sm text-muted-foreground">{p.note}</p>}</div>)}</CardContent></Card>}
  {a.attachments.length>0&&<Card><CardHeader><CardTitle>Fotos e arquivos</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{a.attachments.map(x=>x.mimeType?.startsWith("image/")?<a key={x.id} href={x.url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-lg border"><img src={x.url} alt={x.name} className="h-40 w-full object-cover"/><p className="truncate p-2 text-xs">{x.name}</p></a>:<Button key={x.id} variant="outline" asChild><a href={x.url} target="_blank" rel="noreferrer"><FileText className="h-4 w-4"/>{x.name}</a></Button>)}</div></CardContent></Card>}
  {a.signatures.length>0&&<Card><CardHeader><CardTitle>Assinaturas</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{a.signatures.map(s=><div key={s.id} className="rounded-md border p-3"><img src={s.dataUrl} alt={`Assinatura de ${s.signerName}`} className="h-20 w-full object-contain"/><p className="font-medium">{s.signerName}</p><p className="text-xs text-muted-foreground">{s.role} • {new Date(s.signedAt).toLocaleString("pt-BR")}</p></div>)}</CardContent></Card>}
  <Card><CardHeader><CardTitle>Histórico</CardTitle></CardHeader><CardContent className="space-y-4">{a.history.map(h=><div key={h.id} className="flex gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-primary"/><div><p className="text-sm font-medium">{historyLabels[h.action]||h.action}</p><p className="text-xs text-muted-foreground">{h.user?.name||"Sistema"} • {new Date(h.createdAt).toLocaleString("pt-BR")}</p></div></div>)}</CardContent></Card>
  <SignatureDialog open={signOpen} onOpenChange={setSignOpen} pending={sign.isPending} onSave={v=>sign.mutate(v)}/></div>;
}
function Info({label,value}:{label:string;value?:string|null}){return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm">{value||"—"}</p></div>}
