import crypto from "crypto";
import { Router } from "express";
import { z } from "zod";
import { authenticate } from "../../middlewares/auth";
import { requirePermission } from "../../middlewares/rbac";
import { prisma } from "../../prisma";
import { asyncHandler } from "../../utils/asyncHandler";
import { BadRequestError, NotFoundError } from "../../utils/ApiError";
import { ok } from "../../utils/response";
import { env } from "../../config/env";
import { sendMail, renderInviteEmail } from "../../lib/mailer";

const router = Router();
router.use(authenticate);

async function sendInvite(_accountId: string, name: string, email: string, clientId: string, inviteToken: string) {
  const client = await prisma.client.findUnique({
    where: { id: clientId },
    select: { organization: { select: { name: true, enterprise: { select: { tradeName: true, legalName: true } } } } },
  });
  const companyName =
    client?.organization.enterprise.tradeName || client?.organization.enterprise.legalName || client?.organization.name || "MOBIEER";
  const link = `${env.appUrl}${env.portal.path}/definir-senha?token=${inviteToken}`;
  const mail = renderInviteEmail({ name, companyName, link });
  await sendMail({ to: email, ...mail });
}
const nullable = (max: number) => z.string().trim().max(max).optional().nullable();
const clientSchema = z.object({ name: z.string().trim().min(2).max(255), document: nullable(30), email: z.string().email().optional().nullable().or(z.literal("")), phone: nullable(30), address: nullable(500), notes: nullable(5000), status: z.enum(["ACTIVE", "INACTIVE"]).default("ACTIVE") });
const projectSchema = z.object({ name: z.string().trim().min(2).max(255), description: nullable(5000), status: z.enum(["PLANNING", "ACTIVE", "ON_HOLD", "COMPLETED", "CANCELLED"]).default("PLANNING"), clientId: z.string().min(1), managerId: z.string().optional().nullable(), startAt: z.coerce.date().optional().nullable(), dueAt: z.coerce.date().optional().nullable(), feedbackFormUrl: z.string().url().max(2000).optional().nullable().or(z.literal("")) });

async function nextProjectCode(organizationId: string) {
  const count = await prisma.project.count({ where: { organizationId } });
  for (let n = count + 1; n < count + 1000; n++) {
    const code = `PRJ-${String(n).padStart(4, "0")}`;
    if (!(await prisma.project.findFirst({ where: { organizationId, code }, select: { id: true } }))) return code;
  }
  return `PRJ-${Date.now()}`;
}
const assistanceSchema = z.object({ title: z.string().trim().min(2).max(255), description: z.string().trim().min(2).max(10000), status: z.enum(["OPEN", "TRIAGE", "SCHEDULED", "IN_PROGRESS", "WAITING_CLIENT", "RESOLVED", "CANCELLED"]).default("OPEN"), priority: z.enum(["LOW", "NORMAL", "HIGH", "URGENT"]).default("NORMAL"), clientId: z.string().min(1), projectId: z.string().optional().nullable(), assigneeId: z.string().optional().nullable(), dueAt: z.coerce.date().optional().nullable() });

async function ensureClient(id: string, organizationId: string) { const value = await prisma.client.findFirst({ where: { id, organizationId } }); if (!value) throw new BadRequestError("Cliente inválido"); return value; }
async function ensureProject(id: string, organizationId: string) { const value = await prisma.project.findFirst({ where: { id, organizationId } }); if (!value) throw new BadRequestError("Projeto inválido"); return value; }
async function ensureUser(id: string, organizationId: string) { const value = await prisma.user.findFirst({ where: { id, organizationId, status: "ACTIVE" } }); if (!value) throw new BadRequestError("Responsável inválido"); return value; }
async function audit(userId: string, action: string, entity: string, entityId: string, details?: object) { await prisma.auditLog.create({ data: { userId, action, entity, entityId, details } }); }

router.get("/enterprise", requirePermission("organization.read"), asyncHandler(async (req, res) => { const enterprise = await prisma.enterprise.findUnique({ where: { id: req.user!.enterpriseId }, include: { organizations: { select: { id: true, name: true, _count: { select: { users: true } } } } } }); return ok(res, enterprise); }));
router.patch("/enterprise", requirePermission("settings.manage"), asyncHandler(async (req, res) => { const input = z.object({ legalName: z.string().trim().min(2).max(255).optional(), tradeName: nullable(255), document: nullable(30), email: z.string().email().optional().nullable().or(z.literal("")), phone: nullable(30) }).parse(req.body); const value = await prisma.enterprise.update({ where: { id: req.user!.enterpriseId }, data: input }); await audit(req.user!.id, "ENTERPRISE_UPDATED", "Enterprise", value.id); return ok(res, value, "Empresa atualizada"); }));

router.get("/clients", requirePermission("organization.read"), asyncHandler(async (req, res) => { const search = String(req.query.search ?? "").trim(); const values = await prisma.client.findMany({ where: { organizationId: req.user!.organizationId, ...(search ? { OR: [{ name: { contains: search, mode: "insensitive" } }, { document: { contains: search } }, { email: { contains: search, mode: "insensitive" } }] } : {}) }, include: { _count: { select: { projects: true, assistances: true, kanbanTasks: true } } }, orderBy: { name: "asc" } }); return ok(res, values); }));
router.post("/clients", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const value = await prisma.client.create({ data: { ...clientSchema.parse(req.body), organizationId: req.user!.organizationId } }); await audit(req.user!.id, "CLIENT_CREATED", "Client", value.id, { name: value.name }); return ok(res, value, "Cliente criado"); }));
router.get("/clients/:id", requirePermission("organization.read"), asyncHandler(async (req, res) => { const value = await prisma.client.findFirst({ where: { id: req.params.id, organizationId: req.user!.organizationId }, include: { projects: true, assistances: true, kanbanTasks: { include: { column: { include: { board: { select: { id: true, name: true } } } } } } } }); if (!value) throw new NotFoundError("Cliente não encontrado"); return ok(res, value); }));
router.patch("/clients/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await ensureClient(req.params.id, req.user!.organizationId); const value = await prisma.client.update({ where: { id: req.params.id }, data: clientSchema.partial().parse(req.body) }); await audit(req.user!.id, "CLIENT_UPDATED", "Client", value.id); return ok(res, value, "Cliente atualizado"); }));

router.get("/projects", requirePermission("organization.read"), asyncHandler(async (req, res) => { const search = String(req.query.search ?? "").trim(); const values = await prisma.project.findMany({ where: { organizationId: req.user!.organizationId, ...(req.query.clientId ? { clientId: String(req.query.clientId) } : {}), ...(search ? { OR: [{ name: { contains: search, mode: "insensitive" } }, { code: { contains: search, mode: "insensitive" } }] } : {}) }, include: { client: { select: { id: true, name: true } }, manager: { select: { id: true, name: true } }, _count: { select: { assistances: true, kanbanTasks: true } } }, orderBy: { updatedAt: "desc" } }); return ok(res, values); }));
router.post("/projects", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const input = projectSchema.parse(req.body); await ensureClient(input.clientId, req.user!.organizationId); if (input.managerId) await ensureUser(input.managerId, req.user!.organizationId); const code = await nextProjectCode(req.user!.organizationId); const value = await prisma.project.create({ data: { ...input, code, organizationId: req.user!.organizationId } }); await audit(req.user!.id, "PROJECT_CREATED", "Project", value.id, { code: value.code }); return ok(res, value, "Projeto criado"); }));
router.patch("/projects/:id", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await ensureProject(req.params.id, req.user!.organizationId); const input = projectSchema.partial().parse(req.body); if (input.clientId) await ensureClient(input.clientId, req.user!.organizationId); if (input.managerId) await ensureUser(input.managerId, req.user!.organizationId); const value = await prisma.project.update({ where: { id: req.params.id }, data: { ...input, feedbackFormUrl: input.feedbackFormUrl === "" ? null : input.feedbackFormUrl, completedAt: input.status === "COMPLETED" ? new Date() : input.status ? null : undefined } }); await audit(req.user!.id, "PROJECT_UPDATED", "Project", value.id); return ok(res, value, "Projeto atualizado"); }));
router.get("/projects/:id", requirePermission("organization.read"), asyncHandler(async (req, res) => { const value = await prisma.project.findFirst({ where: { id: req.params.id, organizationId: req.user!.organizationId }, include: { client: { select: { id: true, name: true } }, manager: { select: { id: true, name: true } }, _count: { select: { assistances: true, kanbanTasks: true, documents: true } } } }); if (!value) throw new NotFoundError("Projeto não encontrado"); return ok(res, value); }));

// ---- Contas de acesso do cliente ao portal ----
router.get("/clients/:id/accounts", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await ensureClient(req.params.id, req.user!.organizationId); const values = await prisma.clientAccount.findMany({ where: { clientId: req.params.id }, select: { id: true, name: true, email: true, status: true, lastLogin: true, inviteExpiry: true, createdAt: true }, orderBy: { createdAt: "asc" } }); return ok(res, values); }));
router.post("/clients/:id/accounts", requirePermission("organization.manage"), asyncHandler(async (req, res) => { const client = await ensureClient(req.params.id, req.user!.organizationId); const input = z.object({ name: z.string().trim().min(2).max(255), email: z.string().email() }).parse(req.body); const email = input.email.toLowerCase(); if (await prisma.clientAccount.findUnique({ where: { email } })) throw new BadRequestError("Já existe uma conta com este e-mail"); const inviteToken = crypto.randomBytes(32).toString("hex"); const account = await prisma.clientAccount.create({ data: { clientId: client.id, name: input.name, email, status: "INVITED", inviteToken, inviteExpiry: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), createdById: req.user!.id } }); await sendInvite(account.id, account.name, account.email, client.id, inviteToken); await audit(req.user!.id, "CLIENT_ACCOUNT_INVITED", "ClientAccount", account.id, { email }); return ok(res, { id: account.id, name: account.name, email: account.email, status: account.status }, "Convite enviado"); }));
router.post("/clients/:id/accounts/:accountId/resend", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await ensureClient(req.params.id, req.user!.organizationId); const account = await prisma.clientAccount.findFirst({ where: { id: req.params.accountId, clientId: req.params.id } }); if (!account) throw new NotFoundError("Conta não encontrada"); if (account.status === "ACTIVE") throw new BadRequestError("Esta conta já está ativa"); const inviteToken = crypto.randomBytes(32).toString("hex"); await prisma.clientAccount.update({ where: { id: account.id }, data: { status: "INVITED", inviteToken, inviteExpiry: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) } }); await sendInvite(account.id, account.name, account.email, req.params.id, inviteToken); await audit(req.user!.id, "CLIENT_ACCOUNT_INVITE_RESENT", "ClientAccount", account.id); return ok(res, { id: account.id }, "Convite reenviado"); }));
router.patch("/clients/:id/accounts/:accountId", requirePermission("organization.manage"), asyncHandler(async (req, res) => { await ensureClient(req.params.id, req.user!.organizationId); const account = await prisma.clientAccount.findFirst({ where: { id: req.params.accountId, clientId: req.params.id } }); if (!account) throw new NotFoundError("Conta não encontrada"); const input = z.object({ status: z.enum(["ACTIVE", "DISABLED"]) }).parse(req.body); if (input.status === "ACTIVE" && !account.passwordHash) throw new BadRequestError("A conta ainda não definiu senha pelo convite"); const value = await prisma.clientAccount.update({ where: { id: account.id }, data: { status: input.status }, select: { id: true, status: true } }); await audit(req.user!.id, "CLIENT_ACCOUNT_UPDATED", "ClientAccount", account.id, { status: input.status }); return ok(res, value, "Conta atualizada"); }));

router.get("/assistances", requirePermission("organization.read"), asyncHandler(async (req, res) => { const values = await prisma.assistanceTicket.findMany({ where: { organizationId: req.user!.organizationId, ...(req.query.status ? { status: req.query.status as never } : {}), ...(req.query.assigneeId ? { assigneeId: String(req.query.assigneeId) } : {}) }, include: { client: { select: { id: true, name: true } }, project: { select: { id: true, code: true, name: true } }, assignee: { select: { id: true, name: true } }, _count: { select: { kanbanTasks: true } } }, orderBy: { updatedAt: "desc" } }); return ok(res, values); }));
router.post("/assistances", requirePermission("organization.tasks.create"), asyncHandler(async (req, res) => { const input = assistanceSchema.parse(req.body); await ensureClient(input.clientId, req.user!.organizationId); if (input.projectId) { const p = await ensureProject(input.projectId, req.user!.organizationId); if (p.clientId !== input.clientId) throw new BadRequestError("O projeto não pertence ao cliente informado"); } if (input.assigneeId) await ensureUser(input.assigneeId, req.user!.organizationId); const count = await prisma.assistanceTicket.count({ where: { organizationId: req.user!.organizationId } }); const number = `AST-${String(count + 1).padStart(5, "0")}`; const value = await prisma.assistanceTicket.create({ data: { ...input, number, organizationId: req.user!.organizationId, createdById: req.user!.id } }); await audit(req.user!.id, "ASSISTANCE_CREATED", "AssistanceTicket", value.id, { number }); if (value.assigneeId && value.assigneeId !== req.user!.id) await prisma.notification.create({ data: { type: "INFO", title: "Nova assistência atribuída", message: `${number} — ${value.title}`, userId: value.assigneeId } }); return ok(res, value, "Assistência criada"); }));
router.patch("/assistances/:id", requirePermission("organization.tasks.edit.all"), asyncHandler(async (req, res) => { const current = await prisma.assistanceTicket.findFirst({ where: { id: req.params.id, organizationId: req.user!.organizationId } }); if (!current) throw new NotFoundError("Assistência não encontrada"); const input = assistanceSchema.partial().parse(req.body); if (input.clientId) await ensureClient(input.clientId, req.user!.organizationId); if (input.projectId) await ensureProject(input.projectId, req.user!.organizationId); if (input.assigneeId) await ensureUser(input.assigneeId, req.user!.organizationId); const value = await prisma.assistanceTicket.update({ where: { id: current.id }, data: { ...input, resolvedAt: input.status === "RESOLVED" ? new Date() : input.status ? null : undefined } }); await audit(req.user!.id, "ASSISTANCE_UPDATED", "AssistanceTicket", value.id, { from: current.status, to: value.status }); return ok(res, value, "Assistência atualizada"); }));

export default router;
