import { useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BriefcaseBusiness, Building2, Headphones, Plus } from "lucide-react";
import { toast } from "sonner";
import { apiGet, apiPost } from "@/services/api";
import { useAuth } from "@/hooks/use-auth";
import { PageHeader } from "@/components/page-header";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { EmptyState, PageSkeleton } from "@/components/ui/states";

type Client={id:string;name:string;document?:string|null;email?:string|null;phone?:string|null;status:string;_count:{projects:number;assistances:number;kanbanTasks:number}};
type Project={id:string;code:string;name:string;status:string;client:{id:string;name:string};manager?:{name:string}|null;_count:{assistances:number;kanbanTasks:number}};
type Assistance={id:string;number:string;title:string;status:string;priority:string;client:{id:string;name:string};project?:{name:string}|null;assignee?:{name:string}|null};
type Person={id:string;name:string};
const statusLabel:Record<string,string>={ACTIVE:"Ativo",INACTIVE:"Inativo",PLANNING:"Planejamento",ON_HOLD:"Pausado",COMPLETED:"Concluído",CANCELLED:"Cancelado",OPEN:"Aberto",TRIAGE:"Triagem",SCHEDULED:"Agendado",IN_PROGRESS:"Em andamento",WAITING_CLIENT:"Aguardando cliente",RESOLVED:"Resolvido"};

export function BusinessPage(){const qc=useQueryClient();const{can}=useAuth();const[dialog,setDialog]=useState<"client"|"project"|"assistance"|null>(null);const[clientForm,setClientForm]=useState({name:"",document:"",email:"",phone:""});const[projectForm,setProjectForm]=useState({name:"",clientId:"",description:""});const[helpForm,setHelpForm]=useState({title:"",description:"",clientId:"",projectId:"",assigneeId:"",priority:"NORMAL"});
const clients=useQuery({queryKey:["business-clients"],queryFn:()=>apiGet<{data:Client[]}>("/business/clients")});const projects=useQuery({queryKey:["business-projects"],queryFn:()=>apiGet<{data:Project[]}>("/business/projects")});const helps=useQuery({queryKey:["business-assistances"],queryFn:()=>apiGet<{data:Assistance[]}>("/business/assistances")});const people=useQuery({queryKey:["kanban-people"],queryFn:()=>apiGet<{data:Person[]}>("/organization/people")});
const refresh=()=>{qc.invalidateQueries({queryKey:["business-clients"]});qc.invalidateQueries({queryKey:["business-projects"]});qc.invalidateQueries({queryKey:["business-assistances"]})};
const save=useMutation({mutationFn:()=>dialog==="client"?apiPost("/business/clients",clientForm):dialog==="project"?apiPost("/business/projects",projectForm):apiPost("/business/assistances",{...helpForm,projectId:helpForm.projectId||null,assigneeId:helpForm.assigneeId||null}),onSuccess:()=>{refresh();setDialog(null);toast.success("Cadastro salvo")},onError:e=>toast.error((e as Error).message)});
if(clients.isLoading||projects.isLoading||helps.isLoading)return <PageSkeleton/>;return <div className="space-y-6"><PageHeader title="Clientes, projetos e assistência" description="Entidades compartilhadas pelos processos e tarefas da MOBIEER."/><Tabs defaultValue="clients"><TabsList><TabsTrigger value="clients">Clientes</TabsTrigger><TabsTrigger value="projects">Projetos</TabsTrigger><TabsTrigger value="assistances">Assistência</TabsTrigger></TabsList>
<TabsContent value="clients" className="space-y-4"><Toolbar title="Clientes" canCreate={can("organization.manage")} onCreate={()=>setDialog("client")}/><Grid empty="Nenhum cliente cadastrado">{clients.data?.data.map(c=><EntityCard key={c.id} icon={Building2} title={c.name} badge={statusLabel[c.status]} description={[c.document,c.email,c.phone].filter(Boolean).join(" · ")} footer={`${c._count.projects} projetos · ${c._count.kanbanTasks} tarefas`}/>)}</Grid></TabsContent>
<TabsContent value="projects" className="space-y-4"><Toolbar title="Projetos" canCreate={can("organization.manage")} onCreate={()=>setDialog("project")}/><Grid empty="Nenhum projeto cadastrado">{projects.data?.data.map(p=><Link key={p.id} to={`/clientes-projetos/${p.id}`} className="block"><EntityCard icon={BriefcaseBusiness} title={`${p.code} — ${p.name}`} badge={statusLabel[p.status]} description={`Cliente: ${p.client.name}`} footer={`${p._count.assistances} assistências · ${p._count.kanbanTasks} tarefas`}/></Link>)}</Grid></TabsContent>
<TabsContent value="assistances" className="space-y-4"><Toolbar title="Assistências" canCreate={can("organization.tasks.create")} onCreate={()=>setDialog("assistance")}/><Grid empty="Nenhuma assistência cadastrada">{helps.data?.data.map(a=><EntityCard key={a.id} icon={Headphones} title={`${a.number} — ${a.title}`} badge={statusLabel[a.status]} description={`Cliente: ${a.client.name}`} footer={`${a.assignee?.name||"Sem responsável"} · Prioridade ${a.priority.toLowerCase()}`}/>)}</Grid></TabsContent></Tabs>
<Dialog open={!!dialog} onOpenChange={v=>!v&&setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog==="client"?"Novo cliente":dialog==="project"?"Novo projeto":"Nova assistência"}</DialogTitle></DialogHeader>{dialog==="client"&&<div className="grid gap-3 sm:grid-cols-2"><Field label="Nome"><Input value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/></Field><Field label="Documento"><Input value={clientForm.document} onChange={e=>setClientForm({...clientForm,document:e.target.value})}/></Field><Field label="E-mail"><Input value={clientForm.email} onChange={e=>setClientForm({...clientForm,email:e.target.value})}/></Field><Field label="Telefone"><Input value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})}/></Field></div>}{dialog==="project"&&<div className="space-y-3"><Field label="Nome"><Input value={projectForm.name} onChange={e=>setProjectForm({...projectForm,name:e.target.value})}/></Field><Field label="Cliente"><Picker value={projectForm.clientId} onChange={v=>setProjectForm({...projectForm,clientId:v})} items={clients.data?.data??[]}/></Field><Field label="Descrição"><Textarea value={projectForm.description} onChange={e=>setProjectForm({...projectForm,description:e.target.value})}/></Field></div>}{dialog==="assistance"&&<div className="space-y-3"><Field label="Título"><Input value={helpForm.title} onChange={e=>setHelpForm({...helpForm,title:e.target.value})}/></Field><Field label="Descrição"><Textarea value={helpForm.description} onChange={e=>setHelpForm({...helpForm,description:e.target.value})}/></Field><Field label="Cliente"><Picker value={helpForm.clientId} onChange={v=>setHelpForm({...helpForm,clientId:v,projectId:""})} items={clients.data?.data??[]}/></Field><Field label="Projeto"><Picker value={helpForm.projectId} onChange={v=>setHelpForm({...helpForm,projectId:v})} items={(projects.data?.data??[]).filter(p=>!helpForm.clientId||p.client.id===helpForm.clientId)}/></Field><Field label="Responsável"><Picker value={helpForm.assigneeId} onChange={v=>setHelpForm({...helpForm,assigneeId:v})} items={people.data?.data??[]}/></Field></div>}<DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>Cancelar</Button><Button disabled={save.isPending} onClick={()=>save.mutate()}>Salvar</Button></DialogFooter></DialogContent></Dialog></div>}
function Toolbar({title,canCreate,onCreate}:{title:string;canCreate:boolean;onCreate:()=>void}){return <div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2>{canCreate&&<Button size="sm" onClick={onCreate}><Plus className="h-4 w-4"/>Adicionar</Button>}</div>}
function Grid({children,empty}:{children:React.ReactNode;empty:string}){const items=Array.isArray(children)?children.filter(Boolean):children;return Array.isArray(items)&&items.length===0?<EmptyState title={empty}/>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{children}</div>}
function EntityCard({icon:Icon,title,badge,description,footer}:{icon:typeof Building2;title:string;badge:string;description:string;footer:string}){return <Card><CardHeader><CardTitle className="flex items-start gap-2 text-base"><Icon className="mt-0.5 h-5 w-5 text-primary"/><span className="flex-1">{title}</span><Badge variant="secondary">{badge}</Badge></CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p className="text-muted-foreground">{description||"Sem informações de contato"}</p><p className="text-xs">{footer}</p></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Picker({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:{id:string;name:string}[]}){return <Select value={value||"NONE"} onValueChange={v=>onChange(v==="NONE"?"":v)}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent><SelectItem value="NONE">Nenhum</SelectItem>{items.map(i=><SelectItem key={i.id} value={i.id}>{i.name}</SelectItem>)}</SelectContent></Select>}
