import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { CalendarClock, CheckSquare, ChevronLeft, CircleUserRound, GripVertical, SquareKanban, MessageSquare, Paperclip, Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { apiGet, apiPatch, apiPost, apiUpload } from "@/services/api";
import { useAuth } from "@/hooks/use-auth";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { EmptyState, PageSkeleton } from "@/components/ui/states";
import { cn } from "@/lib/utils";

type Person = { id: string; name: string; sector?: string | null; position?: string | null };
type LabelType = { id: string; name: string; color: string };
type Checklist = { id: string; title: string; completed: boolean };
type Comment = { id: string; body: string; createdAt: string; author: { id: string; name: string } };
type Task = { id: string; title: string; description?: string | null; priority: "LOW" | "NORMAL" | "HIGH" | "URGENT"; dueAt?: string | null; completedAt?: string | null; assignee?: Person | null; labels: { label: LabelType }[]; checklist: Checklist[]; comments: Comment[]; attachments: { id: string; name: string; url: string }[]; client?: { id: string; name: string } | null; project?: { id: string; code: string; name: string } | null };
type Column = { id: string; name: string; position: number; cardLimit?: number | null; isCompletion: boolean; tasks: Task[] };
type Board = { id: string; name: string; description?: string | null; team?: string | null; visibility: string; owner: Person; labels: LabelType[]; columns: Column[] };
type BoardSummary = { id: string; name: string; description?: string | null; team?: string | null; visibility: string; owner: Person; _count: { columns: number } };
type Client = { id: string; name: string };
type Project = { id: string; code: string; name: string; clientId: string };

const priorityLabel = { LOW: "Baixa", NORMAL: "Normal", HIGH: "Alta", URGENT: "Urgente" };
const priorityClass = { LOW: "bg-slate-500/10 text-slate-600", NORMAL: "bg-blue-500/10 text-blue-700", HIGH: "bg-amber-500/10 text-amber-700", URGENT: "bg-red-500/10 text-red-700" };
const emptyTask = { title: "", description: "", assigneeId: "", priority: "NORMAL", dueAt: "", clientId: "", projectId: "" };

export function OrganizationPage() {
  const { id } = useParams();
  return id ? <KanbanBoard boardId={id} /> : <Boards />;
}

function Boards() {
  const navigate = useNavigate(); const qc = useQueryClient(); const { can } = useAuth();
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: "", description: "", team: "", visibility: "TEAM" });
  const query = useQuery({ queryKey: ["kanban-boards"], queryFn: () => apiGet<{ data: BoardSummary[] }>("/organization/boards") });
  const create = useMutation({ mutationFn: () => apiPost<{ data: Board }>("/organization/boards", form), onSuccess: r => { qc.invalidateQueries({ queryKey: ["kanban-boards"] }); setOpen(false); setForm({ name: "", description: "", team: "", visibility: "TEAM" }); navigate(`/organizacao/${r.data.id}`); }, onError: e => toast.error((e as Error).message) });
  if (query.isLoading) return <PageSkeleton />;
  const boards = query.data?.data ?? [];
  return <div className="space-y-6"><PageHeader title="Organização interna" description="Quadros para equipes, processos e tarefas internas.">{can("organization.manage") && <Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Novo quadro</Button>}</PageHeader>
    {boards.length === 0 ? <EmptyState icon={SquareKanban} title="Nenhum quadro disponível" description="Crie o primeiro quadro para organizar o fluxo da equipe." /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{boards.map(b => <Card key={b.id} className="cursor-pointer transition hover:-translate-y-0.5 hover:shadow-md" onClick={() => navigate(`/organizacao/${b.id}`)}><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle>{b.name}</CardTitle><Badge variant="secondary">{b._count.columns} colunas</Badge></div></CardHeader><CardContent className="space-y-3 text-sm"><p className="line-clamp-2 text-muted-foreground">{b.description || "Sem descrição"}</p><div className="flex justify-between text-xs"><span>{b.team || "Toda a organização"}</span><span>Responsável: {b.owner.name}</span></div></CardContent></Card>)}</div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Novo quadro</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Nome"><Input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></Field><Field label="Descrição"><Textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field><Field label="Equipe ou setor"><Input value={form.team} onChange={e => setForm({ ...form, team: e.target.value })} /></Field><Field label="Visibilidade"><Select value={form.visibility} onValueChange={visibility => setForm({ ...form, visibility })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PRIVATE">Privado</SelectItem><SelectItem value="TEAM">Equipe</SelectItem><SelectItem value="ORGANIZATION">Organização</SelectItem></SelectContent></Select></Field></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button><Button disabled={create.isPending || form.name.trim().length < 2} onClick={() => create.mutate()}>Criar quadro</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function KanbanBoard({ boardId }: { boardId: string }) {
  const navigate = useNavigate(); const qc = useQueryClient(); const { can } = useAuth();
  const [taskOpen, setTaskOpen] = useState(false); const [detail, setDetail] = useState<Task | null>(null); const [targetColumn, setTargetColumn] = useState(""); const [columnOpen, setColumnOpen] = useState(false); const [columnName, setColumnName] = useState("");
  const [search, setSearch] = useState(""); const [priority, setPriority] = useState("ALL"); const [form, setForm] = useState(emptyTask);
  const query = useQuery({ queryKey: ["kanban-board", boardId], queryFn: () => apiGet<{ data: Board }>(`/organization/boards/${boardId}`) });
  const people = useQuery({ queryKey: ["kanban-people"], queryFn: () => apiGet<{ data: Person[] }>("/organization/people") });
  const clients = useQuery({ queryKey: ["business-clients"], queryFn: () => apiGet<{ data: Client[] }>("/business/clients") });
  const projects = useQuery({ queryKey: ["business-projects"], queryFn: () => apiGet<{ data: Project[] }>("/business/projects") });
  const refresh = () => qc.invalidateQueries({ queryKey: ["kanban-board", boardId] });
  const createTask = useMutation({ mutationFn: () => apiPost("/organization/tasks", { ...form, columnId: targetColumn, assigneeId: form.assigneeId || null, dueAt: form.dueAt ? new Date(form.dueAt).toISOString() : null, clientId: form.clientId || null, projectId: form.projectId || null }), onSuccess: () => { refresh(); setTaskOpen(false); setForm(emptyTask); toast.success("Tarefa criada"); }, onError: e => toast.error((e as Error).message) });
  const move = useMutation({ mutationFn: ({ taskId, columnId }: { taskId: string; columnId: string }) => apiPatch(`/organization/tasks/${taskId}/move`, { columnId, position: 0 }), onSuccess: refresh, onError: e => toast.error((e as Error).message) });
  const addColumn = useMutation({ mutationFn: () => apiPost(`/organization/boards/${boardId}/columns`, { name: columnName }), onSuccess: () => { refresh(); setColumnOpen(false); setColumnName(""); }, onError: e => toast.error((e as Error).message) });
  if (query.isLoading) return <PageSkeleton />; const board = query.data?.data; if (!board) return <EmptyState title="Quadro não encontrado" />;
  const columns = board.columns.map(c => ({ ...c, tasks: c.tasks.filter(t => (!search || `${t.title} ${t.description ?? ""}`.toLowerCase().includes(search.toLowerCase())) && (priority === "ALL" || t.priority === priority)) }));
  const openCreate = (columnId: string) => { setTargetColumn(columnId); setForm(emptyTask); setTaskOpen(true); };
  return <div className="space-y-5"><PageHeader title={board.name} description={board.description || `${board.team || "Organização"} · ${board.owner.name}`}><Button variant="outline" onClick={() => navigate("/organizacao")}><ChevronLeft className="h-4 w-4" />Quadros</Button>{can("organization.manage") && <Button variant="outline" onClick={() => setColumnOpen(true)}><Plus className="h-4 w-4" />Coluna</Button>}</PageHeader>
    <div className="flex flex-col gap-3 rounded-xl border bg-card p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar tarefas" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={priority} onValueChange={setPriority}><SelectTrigger className="sm:w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">Todas as prioridades</SelectItem>{Object.entries(priorityLabel).map(([v,l]) => <SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>
    <div className="flex min-h-[60vh] gap-4 overflow-x-auto pb-4">{columns.map(col => <section key={col.id} className="w-[300px] shrink-0 rounded-xl bg-muted/45 p-3" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const taskId = e.dataTransfer.getData("text/task-id"); if (taskId) move.mutate({ taskId, columnId: col.id }); }}><header className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><h2 className="font-semibold">{col.name}</h2><Badge variant="secondary">{col.tasks.length}{col.cardLimit ? `/${col.cardLimit}` : ""}</Badge></div>{can("organization.tasks.create") && <Button size="icon" variant="ghost" onClick={() => openCreate(col.id)}><Plus className="h-4 w-4" /></Button>}</header><div className="space-y-3">{col.tasks.map(task => <TaskCard key={task.id} task={task} onOpen={() => setDetail(task)} />)}{col.tasks.length === 0 && <div className="rounded-lg border border-dashed p-5 text-center text-xs text-muted-foreground">Solte uma tarefa aqui</div>}</div></section>)}</div>
    <TaskForm open={taskOpen} onOpenChange={setTaskOpen} form={form} setForm={setForm} people={people.data?.data ?? []} clients={clients.data?.data ?? []} projects={projects.data?.data ?? []} pending={createTask.isPending} onSave={() => createTask.mutate()} />
    <TaskDetail task={detail} onClose={() => setDetail(null)} onChanged={refresh} />
    <Dialog open={columnOpen} onOpenChange={setColumnOpen}><DialogContent><DialogHeader><DialogTitle>Nova coluna</DialogTitle></DialogHeader><Field label="Nome"><Input value={columnName} onChange={e => setColumnName(e.target.value)} /></Field><DialogFooter><Button variant="outline" onClick={() => setColumnOpen(false)}>Cancelar</Button><Button disabled={columnName.trim().length < 1 || addColumn.isPending} onClick={() => addColumn.mutate()}>Adicionar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function TaskCard({ task, onOpen }: { task: Task; onOpen: () => void }) {
  const done = task.checklist.filter(i => i.completed).length; const overdue = task.dueAt && !task.completedAt && new Date(task.dueAt) < new Date();
  return <button draggable onDragStart={e => { e.dataTransfer.setData("text/task-id", task.id); e.dataTransfer.effectAllowed = "move"; }} onClick={onOpen} className="w-full cursor-grab rounded-lg border bg-card p-3 text-left shadow-sm transition hover:border-primary/40 hover:shadow active:cursor-grabbing"><div className="mb-2 flex items-start gap-2"><GripVertical className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"/><span className="flex-1 text-sm font-semibold">{task.title}</span></div>{task.labels.length > 0 && <div className="mb-2 flex flex-wrap gap-1">{task.labels.map(x => <span key={x.label.id} className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] text-primary">{x.label.name}</span>)}</div>}<div className="flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground"><span className={cn("rounded px-1.5 py-0.5", priorityClass[task.priority])}>{priorityLabel[task.priority]}</span>{task.dueAt && <span className={cn("flex items-center gap-1", overdue && "font-semibold text-destructive")}><CalendarClock className="h-3 w-3"/>{new Date(task.dueAt).toLocaleDateString("pt-BR")}</span>}{task.checklist.length > 0 && <span className="flex items-center gap-1"><CheckSquare className="h-3 w-3"/>{done}/{task.checklist.length}</span>}{task.comments.length > 0 && <span className="flex items-center gap-1"><MessageSquare className="h-3 w-3"/>{task.comments.length}</span>}{task.assignee && <span className="ml-auto flex items-center gap-1"><CircleUserRound className="h-3 w-3"/>{task.assignee.name.split(" ")[0]}</span>}</div></button>;
}

function TaskForm({ open, onOpenChange, form, setForm, people, clients, projects, pending, onSave }: { open: boolean; onOpenChange: (v:boolean)=>void; form: typeof emptyTask; setForm: (v:typeof emptyTask)=>void; people: Person[]; clients: Client[]; projects: Project[]; pending:boolean; onSave:()=>void }) {
  const availableProjects = projects.filter(p => !form.clientId || p.clientId === form.clientId);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Nova tarefa</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Título" className="sm:col-span-2"><Input value={form.title} onChange={e => setForm({ ...form, title:e.target.value })}/></Field><Field label="Descrição" className="sm:col-span-2"><Textarea value={form.description} onChange={e => setForm({ ...form, description:e.target.value })}/></Field><Field label="Responsável"><Select value={form.assigneeId || "NONE"} onValueChange={v => setForm({ ...form, assigneeId:v === "NONE" ? "" : v })}><SelectTrigger><SelectValue placeholder="Sem responsável"/></SelectTrigger><SelectContent><SelectItem value="NONE">Sem responsável</SelectItem>{people.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Prioridade"><Select value={form.priority} onValueChange={v => setForm({ ...form, priority:v })}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(priorityLabel).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></Field><Field label="Prazo"><Input type="datetime-local" value={form.dueAt} onChange={e => setForm({ ...form, dueAt:e.target.value })}/></Field><Field label="Cliente"><Select value={form.clientId || "NONE"} onValueChange={v => setForm({ ...form, clientId:v === "NONE" ? "" : v, projectId:"" })}><SelectTrigger><SelectValue placeholder="Sem cliente"/></SelectTrigger><SelectContent><SelectItem value="NONE">Sem cliente</SelectItem>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Projeto"><Select value={form.projectId || "NONE"} onValueChange={v => setForm({ ...form, projectId:v === "NONE" ? "" : v })}><SelectTrigger><SelectValue placeholder="Sem projeto"/></SelectTrigger><SelectContent><SelectItem value="NONE">Sem projeto</SelectItem>{availableProjects.map(p=><SelectItem key={p.id} value={p.id}>{p.code} — {p.name}</SelectItem>)}</SelectContent></Select></Field></div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button disabled={pending || form.title.trim().length < 2} onClick={onSave}>Criar tarefa</Button></DialogFooter></DialogContent></Dialog>;
}

function TaskDetail({ task, onClose, onChanged }: { task: Task | null; onClose:()=>void; onChanged:()=>void }) {
  const [item, setItem] = useState(""); const [comment, setComment] = useState("");
  const detailQuery = useQuery({ queryKey:["kanban-task",task?.id], queryFn:()=>apiGet<{data:Task}>(`/organization/tasks/${task!.id}`), enabled:!!task });
  const current=detailQuery.data?.data??task;
  const changed=()=>{onChanged();detailQuery.refetch()};
  const checklist = useMutation({ mutationFn: (payload:{id?:string;title?:string;completed?:boolean}) => payload.id ? apiPatch(`/organization/checklist/${payload.id}`, { completed:payload.completed }) : apiPost(`/organization/tasks/${task!.id}/checklist`, { title:payload.title }), onSuccess:changed, onError:e=>toast.error((e as Error).message) });
  const commenting = useMutation({ mutationFn:()=>apiPost(`/organization/tasks/${task!.id}/comments`,{body:comment}), onSuccess:()=>{setComment("");changed()}, onError:e=>toast.error((e as Error).message) });
  const upload=useMutation({mutationFn:async(file:File)=>{const uploaded=await apiUpload<{data:{name:string;url:string;mimeType:string;size:number}}>("/organization/uploads",file);return apiPost(`/organization/tasks/${task!.id}/attachments`,uploaded.data)},onSuccess:changed,onError:e=>toast.error((e as Error).message)});
  if (!current) return null; const done=current.checklist.filter(i=>i.completed).length; const progress=current.checklist.length?Math.round(done/current.checklist.length*100):0;
  return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{current.title}</DialogTitle></DialogHeader><div className="space-y-5"><div className="flex flex-wrap gap-2"><Badge className={priorityClass[current.priority]}>{priorityLabel[current.priority]}</Badge>{current.assignee&&<Badge variant="outline">{current.assignee.name}</Badge>}{current.client&&<Badge variant="outline">Cliente: {current.client.name}</Badge>}</div>{current.description&&<p className="whitespace-pre-wrap text-sm text-muted-foreground">{current.description}</p>}
    <section><div className="mb-2 flex items-center justify-between"><h3 className="font-semibold">Checklist</h3><span className="text-xs text-muted-foreground">{done} de {current.checklist.length} — {progress}%</span></div><div className="mb-3 h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${progress}%`}}/></div><div className="space-y-2">{current.checklist.map(i=><label key={i.id} className="flex items-center gap-2 text-sm"><Checkbox checked={i.completed} onCheckedChange={v=>checklist.mutate({id:i.id,completed:v===true})}/><span className={cn(i.completed&&"text-muted-foreground line-through")}>{i.title}</span></label>)}</div><div className="mt-3 flex gap-2"><Input placeholder="Novo item" value={item} onChange={e=>setItem(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&item.trim()){checklist.mutate({title:item});setItem("")}}}/><Button variant="outline" disabled={!item.trim()} onClick={()=>{checklist.mutate({title:item});setItem("")}}>Adicionar</Button></div></section>
    <section><h3 className="mb-2 font-semibold">Comentários</h3><div className="space-y-2">{current.comments.map(c=><div key={c.id} className="rounded-lg bg-muted/50 p-3 text-sm"><div className="mb-1 flex justify-between text-xs text-muted-foreground"><strong>{c.author.name}</strong><span>{new Date(c.createdAt).toLocaleString("pt-BR")}</span></div><p className="whitespace-pre-wrap">{c.body}</p></div>)}</div><div className="mt-3 flex gap-2"><Textarea placeholder="Adicionar comentário" value={comment} onChange={e=>setComment(e.target.value)}/><Button disabled={!comment.trim()||commenting.isPending} onClick={()=>commenting.mutate()}>Comentar</Button></div></section>
    <section><div className="mb-2 flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Paperclip className="h-4 w-4"/>Arquivos</h3><label className="cursor-pointer text-xs font-medium text-primary hover:underline">{upload.isPending?"Enviando...":"Anexar arquivo"}<input type="file" className="sr-only" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt" disabled={upload.isPending} onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate(file);e.target.value=""}}/></label></div>{current.attachments.length===0?<p className="text-xs text-muted-foreground">Nenhum arquivo anexado.</p>:current.attachments.map(a=><a className="block text-sm text-primary hover:underline" href={a.url} target="_blank" rel="noreferrer" key={a.id}>{a.name}</a>)}</section>
  </div></DialogContent></Dialog>;
}

function Field({ label, children, className }: { label:string; children:React.ReactNode; className?:string }) { return <div className={cn("space-y-2",className)}><Label>{label}</Label>{children}</div>; }
