import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes";
import categoriesRoutes from "../modules/categories/categories.routes";
import inventoryRoutes from "../modules/inventory/inventory.routes";
import productsRoutes from "../modules/products/products.routes";
import requisitionsRoutes from "../modules/requisitions/requisitions.routes";
import stockRoutes from "../modules/stock/stock.routes";
import suppliersRoutes from "../modules/suppliers/suppliers.routes";
import usersRoutes from "../modules/users/users.routes";
import warehousesRoutes from "../modules/warehouses/warehouses.routes";
import dashboardRoutes from "../modules/dashboard/dashboard.routes";
import reportsRoutes from "../modules/reports/reports.routes";
import notificationsRoutes from "../modules/notifications/notifications.routes";
import auditRoutes from "../modules/audit/audit.routes";
import searchRoutes from "../modules/search/search.routes";
import settingsRoutes from "../modules/settings/settings.routes";
import stockOperationsRoutes from "../modules/stock-operations/stock-operations.routes";
import organizationRoutes from "../modules/organization/organization.routes";
import businessRoutes from "../modules/business/business.routes";
import documentsRoutes from "../modules/documents/documents.routes";
import portalRoutes from "../modules/portal/portal.routes";
import hrRoutes from "../modules/hr/hr.routes";
import financeRoutes from "../modules/finance/finance.routes";
import templatesRoutes from "../modules/templates/templates.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/products", productsRoutes);
router.use("/categories", categoriesRoutes);
router.use("/suppliers", suppliersRoutes);
router.use("/warehouses", warehousesRoutes);
router.use("/stock", stockRoutes);
router.use("/stock-operations", stockOperationsRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/requisitions", requisitionsRoutes);
router.use("/users", usersRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/audit", auditRoutes);
router.use("/search", searchRoutes);
router.use("/settings", settingsRoutes);
router.use("/organization", organizationRoutes);
router.use("/business", businessRoutes);
router.use("/documents", documentsRoutes);
router.use("/portal", portalRoutes);
router.use("/hr", hrRoutes);
router.use("/finance", financeRoutes);
router.use("/templates", templatesRoutes);

export default router;
